document.write(" <!--Modal Default-->");
document.write("                <div id=\"modal-default\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-default-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-default-label\" class=\"modal-title\">Modal Default<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">Modal body goes here<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Left Footer-->");
document.write("                <div id=\"modal-left-footer\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-left-footer-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-left-footer-label\" class=\"modal-title\">Modal Left Footer<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">Modal body goes here<\/div>");
document.write("                            <div class=\"modal-footer modal-footer-left\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Header Color Primary-->");
document.write("                <div id=\"modal-header-primary\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-header-primary-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header modal-header-primary\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-header-primary-label\" class=\"modal-title\">Modal Header Primary<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">Modal body goes here<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Responsive-->");
document.write("                <div id=\"modal-responsive\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-responsive-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-responsive-label\" class=\"modal-title\">Modal Responsive<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">");
document.write("                                <div class=\"row\">");
document.write("                                    <div class=\"col-md-6\">");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                    <\/div>");
document.write("                                    <div class=\"col-md-6\">");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                        <div class=\"mbm\"><input type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                                    <\/div>");
document.write("                                <\/div>");
document.write("                            <\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Stackable-->");
document.write("                <div id=\"modal-stackable\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-stackable-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-stackable-label\" class=\"modal-title\">Modal Stackable<\/h4><\/div>");
document.write("                            <div class=\"modal-body\"><p>One fine body…<\/p>");
document.write("");
document.write("                                <p>One fine body…<\/p>");
document.write("");
document.write("                                <p>One fine body…<\/p><input type=\"text\" data-tabindex=\"1\"");
document.write("                                                            class=\"form-control mbm\"\/><input type=\"text\"");
document.write("                                                                                             data-tabindex=\"2\"");
document.write("                                                                                             class=\"form-control mbm\"\/><a");
document.write("                                        data-toggle=\"modal\" data-target=\"#stack2\" class=\"btn btn-primary\">Launch");
document.write("                                    modal<\/a><\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <div id=\"stack2\" tabindex=\"-1\" data-focus-on=\"input:first\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4>Stack Two<\/h4><\/div>");
document.write("                            <div class=\"modal-body\"><p>One fine body…<\/p>");
document.write("");
document.write("                                <p>One fine body…<\/p><input type=\"text\" data-tabindex=\"1\"");
document.write("                                                            class=\"form-control mbm\"\/><input type=\"text\"");
document.write("                                                                                             data-tabindex=\"2\"");
document.write("                                                                                             class=\"form-control mbm\"\/><a");
document.write("                                        data-toggle=\"modal\" href=\"#stack3\" class=\"btn btn-default\">Launch modal<\/a>");
document.write("                            <\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Ok<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <div id=\"stack3\" tabindex=\"-1\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4>Stack Three<\/h4><\/div>");
document.write("                            <div class=\"modal-body\"><p>One fine body…<\/p><input type=\"text\" data-tabindex=\"1\"");
document.write("                                                                                class=\"form-control mbm\"\/><input");
document.write("                                    type=\"text\" data-tabindex=\"2\" class=\"form-control mbm\"\/><\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Ok<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Full Width-->");
document.write("                <div id=\"modal-full-width\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-full-width-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog modal-full-width\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-full-width-label\" class=\"modal-title\">Modal Full Width<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">Modal body goes here<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Wide Width-->");
document.write("                <div id=\"modal-wide-width\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-wide-width-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog modal-wide-width\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-wide-width-label\" class=\"modal-title\">Modal Wide Width<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">Modal body goes here<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">Save changes<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Static-->");
document.write("                <div id=\"modal-static\" tabindex=\"-1\" data-backdrop=\"static\" data-keyboard=\"false\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-body\"><p>Would you like to continue with some arbitrary task?<\/p><\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Cancel<\/button>");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-primary\">Continue Task");
document.write("                                <\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Long-->");
document.write("                <div id=\"modal-long\" tabindex=\"-1\" data-replace=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4>A Fairly Long Modal<\/h4><\/div>");
document.write("                            <div class=\"modal-body\"><a data-toggle=\"modal\" href=\"#modal-notlong\"");
document.write("                                                       style=\"position: absolute; top: 50%; right: 12px\"");
document.write("                                                       class=\"btn btn-primary\">Not So Long Modal<\/a><img");
document.write("                                    style=\"height: 800px;\" src=\"http:\/\/i.imgur.com\/KwPYo.jpg\"\/><\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <div id=\"modal-notlong\" tabindex=\"-1\" data-replace=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4>Not That Long<\/h4><\/div>");
document.write("                            <div class=\"modal-body\"><img style=\"height: 300px;\" src=\"http:\/\/i.imgur.com\/KwPYo.jpg\"\/>");
document.write("                            <\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Alert-->");
document.write("                <div id=\"modal-alert\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-body\">Hello world !<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-primary\">Ok<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Confirm-->");
document.write("                <div id=\"modal-confirm\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-body\">Are you sure?<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                               <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Cancel<\/button>");
document.write("                                <button type=\"button\"  data-dismiss=\"modal\" class=\"btn btn-primary\">Ok<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Custom Dialog-->");
document.write("                <div id=\"modal-custom-dialog\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 class=\"modal-title\">Custom Dialog<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">I am a custom dialog<\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-success\">Success !<\/button>");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-info\">Information !<\/button>");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-danger\">Danger !<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Login-->");
document.write("                <div id=\"modal-login\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-login-label\" aria-hidden=\"true\"");
document.write("                     class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-login-label\" class=\"modal-title\">Login<\/h4><\/div>");
document.write("                            <div class=\"modal-body\">");
document.write("                                <div class=\"form\">");
document.write("                                    <form class=\"form-horizontal\">");
document.write("                                        <div class=\"form-group\"><label for=\"username\" class=\"control-label col-md-3\">Username<\/label>");
document.write("");
document.write("                                            <div class=\"col-md-9\"><input id=\"username\" type=\"text\"");
document.write("                                                                         class=\"form-control\"\/><\/div>");
document.write("                                        <\/div>");
document.write("                                        <div class=\"form-group\"><label for=\"password\" class=\"control-label col-md-3\">Password<\/label>");
document.write("");
document.write("                                            <div class=\"col-md-9\"><input id=\"password\" type=\"password\"");
document.write("                                                                         class=\"form-control\"\/><\/div>");
document.write("                                        <\/div>");
document.write("                                        <div class=\"form-group\">");
document.write("                                            <div class=\"col-md-9 col-md-offset-3\">");
document.write("                                                <button type=\"button\" class=\"btn btn-primary\">Login<\/button>");
document.write("                                            <\/div>");
document.write("                                        <\/div>");
document.write("                                    <\/form>");
document.write("                                <\/div>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--Modal Prompt-->");
document.write("                <div id=\"modal-prompt\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal-prompt-label\"");
document.write("                     aria-hidden=\"true\" class=\"modal fade\">");
document.write("                    <div class=\"modal-dialog\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" aria-hidden=\"true\"");
document.write("                                        class=\"close\">&times;<\/button>");
document.write("                                <h4 id=\"modal-prompt-label\" class=\"modal-title\">What is your name?<\/h4><\/div>");
document.write("                            <div class=\"modal-body\"><input id=\"fullname\" type=\"text\" class=\"form-control\"\/><\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">Close<\/button>");
document.write("                                <button type=\"button\" class=\"btn btn-primary\">OK<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
