/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
var numberofRows = 0;
var autogeneratednumber1;
function getVoucherNumber() {
    $.post(server_base_url + "financial/transaction/JournalVoucher/GetNewVoucherNumber", {
    }).done(function (data) {
        var val = data.voucherNo;
        autogeneratednumber1 = val;
        return val;
    });
}
function journalVoucherMaster1(divId)
{
    var financialYear = getUserSessionElement(seCurrentFinancialYear);
    var currentFinancialYear = getUserSessionElement(seCurrentFinancialYear);

    if (currentFinancialYear != null || currentFinancialYear != "" || currentFinancialYear != undefined)
    {
        var finyearArray = currentFinancialYear.split("~");
    }
    if (finyearArray != null || finyearArray != "" || finyearArray != undefined)
    {
        var fromFinacialYear = finyearArray[0];
        var toFinacialYear = finyearArray[1];

    }
    $("#dashboardOrderListId").text("").append('<a href="javascript:void(0)" data-toggle="tab" onclick="displayFinanceHorizontalBar()">Financial Management</a> > <a href="javascript:void(0)" data-toggle="tab" onclick="financeTransactionMenuTabs()">Transaction Master</a> > <a href="javascript:void(0)" data-toggle="tab" onclick="journalVoucherMaster1()">Journal Voucher</a>');
    numberofRows = 0;
    var vouchenovalue = "";
    var ddoCode = getUserSessionElement(seDDOId);
    var locationCode = getUserSessionElement(seLocationId);
    $.post(server_base_url + "financial/transaction/JournalVoucher/GetNewVoucherNumber", {
        ddoCode: ddoCode,
        locationCode: locationCode
    }).done(function (data) {
        var val = data[0].voucherNo;
        vouchenovalue = vouchenovalue + val;
        $("#voucherNo").val(val);
        $("#parr").append(vouchenovalue);
    });

    scrolupfunction();
    $("#" + divId).text("").append("<div id='testMainDivId' />");
    $("#testMainDivId").text("").append("<div id='mainTabMenu'/>");
    $("#mainTabMenu").append("<div id='tableHeader'/>");
    if (checkUserPrivelege(pvCreateJournalVoucher)) {
        $("#tableHeader").append("<div id='FirstPanel' class='panel panel-blue' />");
        $("#FirstPanel").append("<div id='firstPanelHeading' class='panel-heading' />");
        $("#firstPanelHeading").append("<h4 id='tableHeader1' class='panel-title' />");
        $("#tableHeader1").append("<div class='panel-title' a data-toggle='collapse' style='font-weight:bold;font-size:15px;' data-parent='#accordion2' href='#collapseOne2'><center>Journal Voucher</center><div class='pull-right' style='position: relative;bottom: 15px;cursor:pointer;' id='coljournalVoucherVoucher'><span class='glyphicon glyphicon-minus-sign'></span></div></div>");
        $("#FirstPanel").append("<div id='collapseOne2' class='panel-collapse collapse in' />");
        $("#coljournalVoucherVoucher").click(function () {
            $("#collapseOne2").toggle();
            if ($("#coljournalVoucherVoucher span").hasClass("glyphicon-minus-sign")) {
                $("#coljournalVoucherVoucher").text("").append("<span class='glyphicon glyphicon-plus-sign'></span>");
            } else {
                $("#coljournalVoucherVoucher").text("").append("<span class='glyphicon glyphicon-minus-sign'></span>");
            }
        });
        $("#collapseOne2").append("<div id='panelMainBody' class = 'panel-body' />");
        $("#panelMainBody").append("<div id='panelRow' class='row' />");
        $("#panelRow").append("<span class='pull-right' style='font-size: 15px;'><strong>Financial Year : " + financialYear + "</strong></span>");

        $("#panelRow").append("<div id='pregsuccessBefore'></div>");

        $("#panelRow").append("<div id='FieldGroup' class='form-group' />");

        $("#FieldGroup").append("<input type='hidden' id='saveorupdate' value='save'>");

        $("#FieldGroup").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="ddoerr"><label for="ddo">DDO <span class="require">*</span> </label><select class="form-control" name="ddo" id="DDO" onchange=getLocationBasedOnDDOInJournalVoucher()></select>'
                + '</div><div class="form-group col-lg-6" id="locationerr"><label for="location">Location<span class="require">*</span> </label><select class="form-control" id="location"></select></div></div>');

        $("#ddoerr").append("<span id='DDOErr'></span>");
        $("#locationerr").append("<span id='locationErr'></span>");

        $("#FieldGroup").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="">Voucher Number <span class="require">*</span> </label><input type="text" readonly id="voucherNo" class="form-control" value="' + vouchenovalue + '">'
                + '</div><div class="form-group col-lg-6" id="vounchernoerr"><label for="location">Manual Voucher Number <span class="require">*</span> </label><input type="text"   id="voucherNumM"  class="form-control"></div></div>');

        $("#vounchernoerr").append("<span id='voucherNumMErr'></span>");

        //

        $("#FieldGroup").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="fundtypeerr"><label for="fundtype">Fund Type <span class="require">*</span> </label><select class="form-control" name="fundType" id="fundType"></select>'
                + '</div><div class="form-group col-lg-6" id="budgetHeaderr"><label for="location">Budget Head <span class="require">*</span> </label><select class="form-control" id="budgetHead"></select></div></div>');
        $("#fundtypeerr").append("<span id='fundTypeErr'></span>");
        $("#budgetHeaderr").append("<span id='budgetHeadErr'></span>");

        $("#FieldGroup").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="ledgercat"><label for="ledger">Ledger Category <span class="require">*</span> </label><select class="form-control" name="ledgerCategory" id="ledgerCategory"></select>'
                + '</div><div class="form-group col-lg-6" id="voucherdateerr"><label for="location">Voucher Date <span class="require">*</span> </label><input type="text"   id="voucherDate"  class="form-control"></div></div>');
        $("#ledgercat").append("<span id='ledgerCategoryErr'></span>");


//   
        $('#voucherDate').datepicker({
            changeYear: true,
            changeMonth: true,
            startDate: fromFinacialYear,
            endDate: toFinacialYear
        });
        $("#voucherDate").keypress(function (event) {
            event.preventDefault();
        });
        $("#voucherdateerr").append("<span id='voucherDateErr'></span>");

        $("#panelMainBody").append("<div id='panelRowForTable' class='row' />");
        $("#panelRowForTable").append("<div id='ReceiptVoucherListAddPanel' class='panel panel-blue' />");
        $("#ReceiptVoucherListAddPanel").append("<div id='ReceiptVoucherListAddPanelHeading' class='panel-heading' />");
        $("#ReceiptVoucherListAddPanelHeading").append("<h4 id='firstHeaderOfReceiptVoucherListAdd' class='panel-title' />");

        $("#firstHeaderOfReceiptVoucherListAdd").append("<div style='font-weight:bold;font-size:15px;' ><center>List of Ledger Amount Detail(s)</center>");

        $("#ReceiptVoucherListAddPanel").append("<div id='collapseOne31' class='panel-collapse collapse in' />");
        $("#collapseOne31").append("<div id='receiptVoucherListAddlistpanelMainBody'  />");
        $("#panelMainBody").append("<div id='receiptVoucherlistAddpanelRow' class='row' />");

        viewJournalVoucherAddList('receiptVoucherlistAddpanelRow');
        addJournalVoucherRows("displayReceiptVoucherAddTableBody");


        $("#panelMainBody").append("<div id='panelRow4' class='row' />");

        $("#panelRow4").append("<div  class='col-xs-3' /><div class='col-xs-3'><button type='button' style='margin-left:10px' value='Add' id='addButtonatSave' class='btn btn-success mr5 pull-right' onclick=addJournalVoucherRows('displayReceiptVoucherAddTableBody')>Add</button></div>");
        $("#panelRow4").append("<div  class='col-xs-3' id='addbuttonmsg' />");

        $("#panelMainBody").append("<div id='panelRow3' class='row' />");
        $("#panelRow3").append("<label class='col-sm-2'>Total Dr Amount(Rs)</label><input type='text'  id='totalDrAmount' value='0' class='col-sm-2' readonly/>");
        $("#panelRow3").append("<div class='col-sm-2'/><label class='col-sm-2'>Total Cr Amount(Rs)</label><input type='text' value='0' id='totalCrAmount' class='col-sm-2' readonly/>");
        $("#panelMainBody").append("<br><div id='panelRowNarration' class='row' />");
        $("#panelRowNarration").append("<label class='col-sm-2'>Short Narration</label><textarea  id='narration' class='col-sm-2' />");
        $("#panelMainBody").append("<br><div id='panelRowNarrationbutton' class='row' />");
        $("#panelRowNarrationbutton").append("<div  class='col-xs-3 ' /><div class='col-xs-1'><button type='button' style='margin-left:10px' value='Add' class='btn btn-success pull-right narration'onclick=addDivRows('panelMainBody') >Show Narrations</button></div>");

        $("#panelMainBody").append("<br><div id='panelRowNarrationvalues' class='row' />");
        //  $("#panelRowNarrationvalues").append('<div class="col-lg-12 narrationval" ><div class="form-group col-lg-6"><label for="fundtype">Narration Type <span class="require">*</span> </label><select class="form-control" name="narrationType" id="narrationType" onchange=getShortdescnarration()></select></div>');

        $("#panelRowNarrationvalues").append('<div class="col-lg-12 narrationval" ><div class="form-group col-lg-6"><label for="fundtype">Narration Type <span class="require">*</span> </label><select class="form-control" name="narrationType" id="narrationType" onchange=getShortdescnarrationJournal()></select></div>');
        $("#panelRowNarrationvalues").append('<div class="col-lg-12 narrationval" ><div class="form-group col-lg-6"><input type="hidden" id="openDiv">');


        $(".narrationval").hide();

        getNarrationListinJournal();

        $("#panelMainBody").append("<br><div id='panelRow5' class='row' />");
        $("#panelRow5").append("<div  class='col-xs-3' /><div class='col-xs-3'><button type='button' style='margin-left:10px' value='Save' class='btn btn-success mr5 pull-right' onclick='journalVoucherValidation()'>Save</button></div><div class='col-xs-2'><button type='button' onclick='journalVoucherMaster1()' class='btn btn-warning mr5 pull-left' name='reset' value='reset'>Reset</button></div>");
        $("#panelRow5").append("<div  class='col-xs-3' id='Savebuttonmsg' />");
    }
    if (checkUserPrivelege(pvViewJournalVoucher)) {
        SearchJournalVoucher();
        //For List
        $("#tableHeader").append("<div id='maritalListPanel' class='panel panel-blue' />");
        $("#maritalListPanel").append("<div id='maritalListPanelHeading' class='panel-heading' />");
        $("#maritalListPanelHeading").append("<h4 id='firstHeader1' class='panel-title' />");
        $("#firstHeader1").append("<div class='panel-title' a data-toggle='collapse' style='font-weight:bold;font-size:15px;' data-parent='#accordion2' href='#collapseOne3'><center>List of Journal Voucher(s)</center><div class='pull-right' style='position: relative;bottom: 15px;cursor:pointer;' id='journalVoucherColDiv'><span class='glyphicon glyphicon-minus-sign'></span></div></div>");
        $("#maritalListPanel").append("<div id='collapseOne3' class='panel-collapse collapse in' />");
        //journalVoucherColDiv
        $("#journalVoucherColDiv").click(function () {
            $("#collapseOne3").toggle();
            if ($("#journalVoucherColDiv span").hasClass("glyphicon-minus-sign")) {
                $("#journalVoucherColDiv").text("").append("<span class='glyphicon glyphicon-plus-sign'></span>");
            } else {
                $("#journalVoucherColDiv").text("").append("<span class='glyphicon glyphicon-minus-sign'></span>");
            }
        });
        $("#collapseOne3").append("<div id='listpanelMainBody' class = 'panel-body' />");
        $("#listpanelMainBody").append("<div id='listpanelRow' class='row' />");
        $("#listpanelMainBody").append("<div id='ErrorMessageDiv1'  />");
    }
    setTimeout(function () {
        viewOptionIdName("budget/master/FundType/View", "", "description", "fundType", "Fund Type");
    }, 200);

//    setTimeout(function () {
//        getDDOforJournalVoucher("", "DDO");
//    }, 200);
    setTimeout(function () {
        viewOption("hrms/common/BudgetHead/View", "", "budgetHead", "budgetHead", "Budget Head");
    }, 300);
    setTimeout(function () {
        fetchLedgerCategoryForJournalVoucher("", "ledgerCategory", "Ledger Category");
    }, 400);
    setTimeout(function () {
        viewJournalVoucherListMaster('listpanelRow');
    }, 200);

    getLoggedInDDOLocationInDropDown("DDO", "location");

}

function getNarrationListinJournal(name)
{
    $.get(server_base_url + "/finance/transactions/GetNarrationTypeForVouchers", {
        VocherName: "Journal Voucher"
    }).done(function (pdata) {
        var mainData = JSON.parse(pdata);

        if (pdata != null) {

            $("#narrationType").text("").append("<option value='' selected>---- Select Narration Type ----</option>");

            for (var i = mainData.length - 1; i >= 0; i--) {

                var subData = mainData[i];
                if (name == subData.idStr)
                {
                    $("#narrationType").append("<option  value='" + subData.idStr + "' selected>" + subData.narationDetail + "</option>");
                } else
                {
                    $("#narrationType").append("<option  value='" + subData.idStr + "' >" + subData.narationDetail + "</option>");
                }



            }
        }
    });
}
function getShortdescnarrationJournal()
{

    var narrationId = $("#narrationType").val();

    $.get(server_base_url + "/financial/account/Naration/ViewList", {
    }).done(function (pdata) {

        var mainData = pdata.result;
        if (pdata != null) {

            for (var i = mainData.length - 1; i >= 0; i--) {

                var subData = mainData[i];

                if (subData._id.$oid == narrationId)
                {
                    $("#narration").val(subData.narationDetail);
                }
            }
        }
    });
}
function addBankDetailRowJournal(DivId, bankAccountNo, bankName, bankAmount, bankRemarks) {
    if (bankAccountNo != null) {

        $("#" + DivId).text("").append("<div id='bankDetailsRow' class='row pal'>");
        $("#bankDetailsRow").append("<div id='bankDetailsRowFieldGroup2' class='form-group' />");

        $("#bankDetailsRowFieldGroup2").append('<div class="col-lg-12 form-group"><div class="form-group col-lg-6"><label for="">Account Number <span class="require">*</span> </label><input type="text" onkeypress="return validateNumber(event)" id="bankAccountNo" class="form-control" value="' + bankAccountNo + '" >'
                + '</div><div class="form-group col-lg-6"><label for="location">Bank Name <span class="require">*</span> </label><select type="text"   id="bankName" class="form-control" ></div></div>');



        $("#bankDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="">Bank Amount <span class="require">*</span> </label><input  type="text" onkeypress="return validateNumber(event)"  id="bankAmount" value="' + bankAmount + '" class="form-control"></select>'
                + '</div><div class="form-group col-lg-6"><label for="">Remarks </label><textarea type="text"  id="bankRemarks" class="form-control"  >' + bankRemarks + '</textarea></div></div>');

        viewOptionIdName("financial/common/BankName/ViewList", bankName, "bankName", "bankName", "Bank");
    } else {

        $("#" + DivId).text("").append("<div id='bankDetailsRow' class='row pal'>");
        $("#bankDetailsRow").append("<div id='bankDetailsRowFieldGroup2' class='form-group' />");

        $("#bankDetailsRowFieldGroup2").append('<div class="col-lg-12 form-group"><div class="form-group col-lg-6"><label for="">Account Number <span class="require">*</span> </label><input type="text" onkeypress="return validateNumber(event)" id="bankAccountNo" class="form-control" >'
                + '</div><div class="form-group col-lg-6"><label for="location">Bank Name <span class="require">*</span> </label><select type="text"   id="bankName" class="form-control" ></div></div>');
        $("#bankDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="">Bank Amount <span class="require">*</span> </label><input  type="text" onkeypress="return validateNumber(event)"   id="bankAmount"  class="form-control"></select>'
                + '</div><div class="form-group col-lg-6"><label for="">Remarks </label><textarea type="text"  id="bankRemarks" class="form-control"  ></textarea></div></div>');
        viewOptionIdName("financial/common/BankName/ViewList", "", "bankName", "bankName", "Bank");
    }
}
function addChequeDetailRowJournal(DivId, chequeNo, chequeDate, chequeBankName, chequeAmount, inFavorOf, checkRemarks) {

    rat = 0;
    if (chequeNo != null) {
        $("#" + DivId).text("").append("<div id='chequeDetailsRow' class='row pal'>");
        $("#chequeDetailsRow").append("<div id='chequeDetailsRowFieldGroup2' class='form-group' />");

        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12 form-group"><div class="form-group col-lg-6" id="chequenumerr"><label for="">Cheque Number <span class="require">*</span> </label><input type="text" onkeypress="return validateNumber(event)"  id="chequeNo" class="form-control" value="' + chequeNo + '" >'
                + '</div><div class="form-group col-lg-6" id="chequedateerr"><label for="location">Cheque Date <span class="require">*</span> </label><input type="text"   id="chequeDate" class="form-control" value="' + chequeDate + '"></div></div>');


        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="banknameerr"><label for="">Bank Name <span class="require">*</span> </label><select class="form-control" name="chequeBankName" id="chequeBankName"></select>'
                + '</div><div class="form-group col-lg-6" id="chequeamterr"><label for="location">Cheque Amount <span class="require">*</span> </label><input type="text" onkeypress="return validateNumber(event)" value="' + chequeAmount + '"  id="chequeAmount" class="form-control"></div></div>');

        $("#chequenumerr").append("<span id='chequeNoErr'></span>");
        $("#chequedateerr").append("<span id='chequeDateErr'></span>");
        $("#banknameerr").append("<span id='chequeBankNameErr'></span>");
        $('#chequeDate').datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd-mm-yy",
            yearRange: '-0:+10'
        });
        $("#chequeDate").keypress(function (event) {
            event.preventDefault();
        });

        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="infavourerr"><label for="">In Favor Of <span class="require">*</span> </label><input type="text" onkeypress="return validatealphanumeric(event)" id="inFavorOf" value="' + inFavorOf + '" class="form-control" >'
                + '</div><div class="form-group col-lg-6"><label for="location">Remarks </label><textarea  type="text"   id="chequeRemarks"  class="form-control">' + checkRemarks + '</textarea></div></div>');


        $("#chequeamterr").append("<span id='chequeAmountErr'></span>");
        $("#infavourerr").append("<span id='inFavorOfErr'></span>");



        viewOptionIdName("financial/common/BankName/ViewList", chequeBankName, "bankName", "chequeBankName", "Bank");
    } else {
        $("#" + DivId).text("").append("<div id='chequeDetailsRow' class='row pal' class='form-group'>");
        $("#chequeDetailsRow").append("<div id='chequeDetailsRowFieldGroup2' class='form-group' />");

        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12 form-group"><div class="form-group col-lg-6" id="chequenumerr"><label for="">Cheque Number <span class="require">*</span> </label><input type="text" onkeypress="return validateNumber(event)"  id="chequeNo" class="form-control" >'
                + '</div><div class="form-group col-lg-6" id="chequedateerr"><label for="location">Cheque Date <span class="require">*</span> </label><input type="text" onkeypress="return false"  id="chequeDate" class="form-control"></div></div>');


        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="banknameerr"><label for="">Bank Name <span class="require">*</span> </label><select class="form-control" name="chequeBankName" id="chequeBankName"></select>'
                + '</div><div class="form-group col-lg-6" id="chequeamterr"><label for="location">Cheque Amount <span class="require">*</span> </label><input type="text" onkeypress="return validateNumber(event)"  id="chequeAmount" class="form-control"></div></div>');


//        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="">Bank Name <span class="require">*</span> </label><select  type="text"   id="chequeBankName" class="form-control">'
//                + '</div><div class="form-group col-lg-6"><label for="checkamount">Cheque Amount <span class="require">*</span> </label><input type="text" id="chequeAmount" class="form-control"></div></div>');


        $("#chequenumerr").append("<span id='chequeNoErr'></span>");
        $("#chequedateerr").append("<span id='chequeDateErr'></span>");
        $("#banknameerr").append("<span id='chequeBankNameErr'></span>");
        $('#chequeDate').datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd-mm-yy",
            yearRange: '-0:+10'
        });

        $("#chequeDetailsRowFieldGroup2").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="infavourerr"><label for="">In Favor Of <span class="require">*</span> </label><input type="text" onkeypress="return validatealphanumeric(event)"  id="inFavorOf" class="form-control" >'
                + '</div><div class="form-group col-lg-6"><label for="location">Remarks</label><textarea  type="text"   id="chequeRemarks"  class="form-control"></textarea></div></div>');


        $("#chequeamterr").append("<span id='chequeAmountErr'></span>");
        $("#infavourerr").append("<span id='inFavorOfErr'></span>");
        viewOptionIdName("financial/common/BankName/ViewList", "", "bankName", "chequeBankName", "Bank");
    }
}

//Adding ReceiptVoucher Rows

function addJournalVoucherRows(DivId, ledgerList)
{
    var sno = 0;
    $('#addbuttonmsg').text("").val("");
    if (($('#totalDrAmount').val() == $('#totalCrAmount').val()) && ($('#totalDrAmount').val() != undefined && $('#totalCrAmount').val() != 0))
    {
        displayLargeErrorMessagesInCenterInRed("addbuttonmsg", "Both Debit and Credit Amount are Same");
    } else
    {
        if (ledgerList != null) {
            for (var i = 0; i < ledgerList.length; i++) {
                sno = sno + 1;
                numberofRows = sno;
                var groupId = 'group' + i;
                var ledgerId = 'ledger' + i;
                var drAmountId = 'drAmount' + i;
                var crAmountId = 'crAmount' + i;
                var drCrId = 'drCrId' + i;
                var ids = "aa" + numberofRows;
                var j = i + 1;
                var narrationId = 'shortNarration' + i;
                $("#" + DivId).append("<tr style='cursor:pointer;' >"
                        + "<td style='cursor:pointer;'>" + sno + "</td>"
                        + "<td style='cursor:pointer;'><select  type='text' onChange=disablefunctionForDrCrForJournalVoucher('" + drCrId + "','" + drAmountId + "','" + crAmountId + "') id='" + drCrId + "' ></select></td>"
                        + "<td style='cursor:pointer;'><select  type='text' name='group' id='" + groupId + "' onchange=getLedgerListForJournal('" + groupId + "','" + ledgerId + "') ></select> <br><select  type='text' name='ledger' id='" + ledgerId + "'></select></td>"
                        + "<td style='cursor:pointer;'><input id='" + drAmountId + "' class='drAmount form-control' type='text' onkeypress='return isNumberKeyValidation(this,event);'  placeholder='Dr.Amount' value='" + ledgerList[i].drAmount + "'></td>" //onblur=checkDrCrAmountAndAddEntryForVoucher('" + drCrId + "')
                        + "<td style='cursor:pointer;'><input id='" + crAmountId + "' class='crAmount form-control' type='text' onkeypress='return isNumberKeyValidation(this,event);' placeholder='Cr.Amount' value='" + ledgerList[i].crAmount + "'></td>" //onblur=checkDrCrAmountAndAddEntryForVoucher('" + drCrId + "')
                        + "<td style='cursor:pointer;'><input type='text' id='" + narrationId + "' placeholder='Short Narration' class='form-control' value='" + ledgerList[i].shortNarration + "'></td>"
                        + "<td style='cursor:pointer;'  id='" + ids + "'>" + ' <button type="button" class="btn mr5 btn-primary" onclick=deleteJournalVoucherListRow(this.parentNode.parentNode.rowIndex,"' + drAmountId + '","' + crAmountId + '") style="align:center;color:white">DELETE</button>' + "</td>"
                        + "</tr></thead>");

                $("#displayReceiptVoucherAddTableBody").on('keydown', "#" + narrationId, function (e) {
                    var keyCode = e.keyCode || e.which;
                    if (keyCode == 9) {
                        //e.preventDefault();
                        // call custom function here
                        addRowJournalUpdateinVouchers('displayReceiptVoucherAddTableBody');
                    }
                });

                getGroupListForOptionsJournal(ledgerList[i].group, groupId, "Group", drCrId);

                getLedgerListForJournal(groupId, ledgerId, ledgerList[i].ledger, ledgerList[i].group);

                getHardCodedOptionsJournalVoucher(ledgerList[i].DrCr, drCrId);
                $('.drAmount').keyup(function () {
                    var sum = 0;
                    $('.drAmount').each(function () {
                        sum += Number($(this).val());
                    });
                    $('#totalDrAmount').val(sum);
                });
                $('.crAmount').keyup(function () {
                    var sum1 = 0;
                    $('.crAmount').each(function () {
                        sum1 += Number($(this).val());
                    });
                    $('#totalCrAmount').val(sum1);
                });

                disablefunctionForDrCrForJournalVoucher(drCrId, drAmountId, crAmountId);

            }

        } else {
            numberofRows++;
            var groupId = 'group' + numberofRows;
            var ledgerId = 'ledger' + numberofRows;
            var drAmountId = 'drAmount' + numberofRows;
            var crAmountId = 'crAmount' + numberofRows;
            var drCrId = 'drCrId' + numberofRows;
            var id = "aa" + numberofRows;

            if (numberofRows == 1)
            {
                $("#" + DivId).append("<tr id='" + id + "' style='cursor:pointer;' >"
                        + "<td style='cursor:pointer;'>" + numberofRows + "</td>"
                        + "<td style='cursor:pointer;'><select  type='text' onChange=disablefunctionForDrCrForJournalVoucher('" + drCrId + "','" + drAmountId + "','" + crAmountId + "') id='" + drCrId + "' ><option val='' selected disabled>---- Select ----</option><option value='Dr'>Dr</option><option  value='Cr'>Cr</option></select></td>"
                        + "<td style='cursor:pointer;'><select  type='text' name='group' id='" + groupId + "' onchange=getLedgerListForJournal('" + groupId + "','" + ledgerId + "')></select> <br><select  type='text' name='ledger' id='" + ledgerId + "'></select></td>"
                        + "<td style='cursor:pointer;'><input id='" + drAmountId + "' class='drAmount form-control' type='text' placeholder='Dr.Amount' onkeypress='return isNumberKeyValidation(this,event);'  disabled></td>" //onblur=checkDrCrAmountAndAddEntryForVoucher('" + drCrId + "')
                        + "<td style='cursor:pointer;'><input id='" + crAmountId + "' class='crAmount form-control' type='text' placeholder='Cr.Amount' onkeypress='return isNumberKeyValidation(this,event);' disabled></td>" //onblur=checkDrCrAmountAndAddEntryForVoucher('" + drCrId + "')
                        + "<td style='cursor:pointer;'><input type='text' id='shortNarration1' placeholder='Short Narration'  class='form-control'></td>"
                        + "<td style='cursor:pointer;'><button type='button' class='btn mr5 btn-default'  style='align:center;color:white'>DELETE</button></td>");

                $("#displayReceiptVoucherAddTableBody").on('keydown', '#shortNarration1', function (e) {
                    var keyCode = e.keyCode || e.which;
                    if (keyCode == 9) {
                        // e.preventDefault();
                        // call custom function here
                        addJournalVoucherRows('displayReceiptVoucherAddTableBody');
                    }
                });

            } else
            {
                $("#" + DivId).append("<tr id='" + id + "' style='cursor:pointer;' >"
                        + "<td style='cursor:pointer;'>" + numberofRows + "</td>"
                        + "<td style='cursor:pointer;'><select  type='text' onChange=disablefunctionForDrCrForJournalVoucher('" + drCrId + "','" + drAmountId + "','" + crAmountId + "') id='" + drCrId + "' ><option val='' selected disabled>---- Select ----</option><option value='Dr'>Dr</option><option  value='Cr'>Cr</option></select></td>"
                        + "<td style='cursor:pointer;'><select  type='text' name='group' id='" + groupId + "' onchange=getLedgerListForJournal('" + groupId + "','" + ledgerId + "')></select> <br><select  type='text' name='ledger' id='" + ledgerId + "'></select></td>"
                        + "<td style='cursor:pointer;'><input id='" + drAmountId + "' class='drAmount form-control' type='text' placeholder='Dr.Amount' onkeypress='return isNumberKeyValidation(this,event);'  disabled></td>" //onblur=checkDrCrAmountAndAddEntryForVoucher('" + drCrId + "')
                        + "<td style='cursor:pointer;'><input id='" + crAmountId + "' class='crAmount form-control' type='text' placeholder='Cr.Amount' onkeypress='return isNumberKeyValidation(this,event);' disabled></td>" //onblur=checkDrCrAmountAndAddEntryForVoucher('" + drCrId + "')
                        + "<td style='cursor:pointer;'><input type='text' id='shortNarration1' placeholder='Short Narration'  class='form-control'></td>"
                        + "<td style='cursor:pointer;'><button type='button' class='btn mr5 btn-primary' onclick=deleteReceiptVoucherListRow(this.parentNode.parentNode.rowIndex,'" + drAmountId + "','" + crAmountId + "')  style='align:center;color:white'>DELETE</button></td>");
            }
            $("#" + id).append("</tr></thead>");

            $("#" + drCrId).attr("onchange", "getGroupListForOptionsJournal('','" + groupId + "', 'Group','" + drCrId + "');disablefunctionForDrCrForJournalVoucher('" + drCrId + "','" + drAmountId + "','" + crAmountId + "')");

            getGroupListForOptionsJournal("", groupId, "Group");
            $('.drAmount').keyup(function () {
                var sum = 0;
                $('.drAmount').each(function () {
                    sum += Number($(this).val());
                });
                $('#totalDrAmount').val(sum);
            });
            $('.crAmount').keyup(function () {
                var sum1 = 0;
                $('.crAmount').each(function () {
                    sum1 += Number($(this).val());
                });
                $('#totalCrAmount').val(sum1);
            });
        }
    }
}
function addRowJournalUpdateinVouchers(DivId)
{
    if (($('#totalDrAmount').val() == $('#totalCrAmount').val()) && ($('#totalDrAmount').val() != undefined && $('#totalCrAmount').val() != 0))
    {
        displayLargeErrorMessagesInCenterInRed("addbuttonmsg", "Both Debit and Credit Amount are Same");
    } else
    {
        numberofRows++;
        var groupId = 'group' + numberofRows;
        var ledgerId = 'ledger' + numberofRows;
        var drAmountId = 'drAmount' + numberofRows;
        var crAmountId = 'crAmount' + numberofRows;
        var drCrId = 'drCrId' + numberofRows;
        var id = "aa" + numberofRows;
        $("#" + DivId).append("<tr id='" + id + "' style='cursor:pointer;' >"
                + "<td style='cursor:pointer;'>" + numberofRows + "</td>"
                + "<td style='cursor:pointer;'><select  onChange=disablefunctionForDrCrForReceiptVoucher('" + drCrId + "','" + drAmountId + "','" + crAmountId + "') id='" + drCrId + "' ><option val='' selected disabled>---- Select ----</option><option value='Dr'>Dr</option><option  value='Cr'>Cr</option></select></td>"
                + "<td style='cursor:pointer;'><select  type='text' name='group' id='" + groupId + "' onchange=getLedgerListForOptions('" + groupId + "','" + ledgerId + "')></select> <br><select  type='text' name='ledger' id='" + ledgerId + "'></select></td>"
                + "<td style='cursor:pointer;'><input id='" + drAmountId + "' class='drAmount form-control' type='text' placeholder='Dr.Amount'   onkeypress='return isNumberKeyValidation(this,event);' disabled></td>"
                + "<td style='cursor:pointer;'><input id='" + crAmountId + "' class='crAmount form-control' type='text' placeholder='Cr.Amount'  onkeypress='return isNumberKeyValidation(this,event);'  disabled></td>"
                + "<td style='cursor:pointer;'><input type='text' id='shortNarration1'  placeholder='Short Narration'  class='form-control'></td>"
                + "<td style='cursor:pointer;'><button type='button' class='btn mr5 btn-primary' onclick=deleteReceiptVoucherListRow(this.parentNode.parentNode.rowIndex,'" + drAmountId + "','" + crAmountId + "')  style='align:center;color:white'>DELETE</button></td>");

        $("#" + id).append("</tr></thead>");
        $("#" + drCrId).attr("onchange", "getGroupListForOptionsJournal('','" + groupId + "', 'Group','" + drCrId + "');disablefunctionForDrCrForJournalVoucher('" + drCrId + "','" + drAmountId + "','" + crAmountId + "')");

        //  getGroupListForOptionsJournal("", groupId, "Group");
        $('.drAmount').keyup(function () {
            var sum = 0;
            $('.drAmount').each(function () {
                sum += Number($(this).val());
            });
            $('#totalDrAmount').val(sum);
        });
        $('.crAmount').keyup(function () {
            var sum1 = 0;
            $('.crAmount').each(function () {
                sum1 += Number($(this).val());
            });
            $('#totalCrAmount').val(sum1);
        });
    }
    setTimeout(function ()
    {
        $('#addbuttonmsg').text("").val("");
    }, 3000);
}
function getLedgerListForJournal(id, ledgerId, ledgerval, groupid)
{
    var group;

    if (groupid == undefined)
    {
        group = $("#" + id).val();
    } else
    {
        group = groupid;
    }

    $.get(server_base_url + "/financial/Transaction/ReceiptVoucher/GetLedger", {
        group: group
    }).done(function (pdata) {
        if (pdata != "500" && pdata != 500 && pdata != "" && pdata != null && pdata != "501")
        {
            $("#" + ledgerId).text("").append("<option value = '' selected>---- Select Ledger----</option>");
            for (var k = 0; k < pdata.length; k++) {

                if (ledgerval == pdata[k].idStr)
                {

                    $("#" + ledgerId).append("<option  value='" + pdata[k].idStr + "' selected>" + pdata[k].ledgerName + "(" + pdata[k].ledgerCode + ")" + "</option>");
                } else
                {
                    $("#" + ledgerId).append("<option  value='" + pdata[k].idStr + "'>" + pdata[k].ledgerName + "(" + pdata[k].ledgerCode + ")" + "</option>");
                }

            }
        } else
        {
            $("#" + ledgerId).text("").append("<option value = '' selected>---- No Data Available ----</option>");
        }
    });

}
function disablefunctionForDrCrForJournalVoucher(drCrId, drAmountId, crAmountId) {
    if ($("#" + drCrId).val() == "Cr") {
        $("#" + drAmountId).attr("disabled", "disabled");
        $("#" + drAmountId).val(0);
        $("#" + crAmountId).removeAttr("disabled");
    } else if ($("#" + drCrId).val() == "Dr") {
        $("#" + crAmountId).val(0);
        $("#" + crAmountId).attr("disabled", "disabled");
        $("#" + drAmountId).removeAttr("disabled");
    } else {
        $("#" + crAmountId).attr("disabled", "disabled");
        $("#" + drAmountId).attr("disabled", "disabled");
    }


}
function  editThisJournalVoucherRow(i) {
    $('table#displayReceiptVoucherAddTable tbody tr').each(function () {

        if ($(this).find("tr:eq(" + i + ")")) {
            var j = i - 1;
            $("#ledgerCategory").val($("table#displayReceiptVoucherAddTable tbody tr:eq(" + j + ")").find('td:eq(0)').text());
            $("#isGrant").val($("table#displayReceiptVoucherAddTable tbody tr:eq(" + j + ")").find('td:eq(1)').text());
            $("#r eceiptVoucherThree").val($("table#displayReceiptVoucherAddTable tbody tr:eq(" + j + ")").find('td:eq(2)').text());
            $("#order").val($("table#displayReceiptVoucherAddTable tbody tr:eq(" + j + ")").find('td:eq(3)').text());
        }
    });
}
//$('#totalDrAmount').val() != $('#totalCrAmount').val()
function deleteJournalVoucherListRow(i, dramount, cramount) {

    var lengthOfROw = getRowsLengthForJournalVoucher();
    if (lengthOfROw != "1") {
        if ($("#" + dramount).val() != null && $("#" + dramount).val() != undefined && $("#" + dramount).val() != "0" && $("#" + dramount).val() != 0)
        {
            var amount = parseInt($('#totalDrAmount').val()) - parseInt($("#" + dramount).val());
            $('#totalDrAmount').val(amount.toString());
        } else if ($("#" + cramount).val() != null && $("#" + cramount).val() != undefined && $("#" + cramount).val() != "0" && $("#" + cramount).val() != 0)
        {

            var totcramount = parseInt($('#totalCrAmount').val()) - parseInt($("#" + cramount).val());

            $('#totalCrAmount').val(totcramount.toString());
        }
        document.getElementById('displayReceiptVoucherAddTableBody').deleteRow(i - 1);
        var slNo = 1;
        $('table#displayReceiptVoucherAddTable tbody tr').each(function (i) {
            var row = $(this).closest('tr');
            //alert(row.find('td:eq(0)').val());
            row.find('td:eq(0)').text(slNo);
            slNo++;
        });
    } else
    {
        $("#aa1").text("").append("<td style='cursor:pointer;'>" + ' <button type="button" class="btn  btn-default mr5" disabled >DELETE</button>' + "</td>");
    }
}
function resetJournalVoucherList()
{
    $("#displayReceiptVoucherAddTableBody").text("");
    resetAllValuesInSpecifiedDiv("panelMainBody");
}

function  viewJournalVoucherAddList(DivId) {
    $("#" + DivId).text("").append("<div class='tab-pane' id='viewReceiptVoucherAdd'/>");
    $("#viewReceiptVoucherAdd").append("<div><h4>&nbsp;&nbsp;Note: Please press tab to generate next row or click on Add Button to generate next row (rows will generate until DR=CR)</h4></div>");
    $("#viewReceiptVoucherAdd").append("<div class='table-responsive' id='viewReceiptVoucherAddTableDiv' />");
    $("#viewReceiptVoucherAddTableDiv").append("<table class='table table-bordered table-striped table-warning mb30' id='displayReceiptVoucherAddTable' />");
    $("#displayReceiptVoucherAddTable").append("<thead class=''><tr>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Sl No.</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>\Dr/Cr</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Particulars</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Dr Amount</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Cr Amount</th>"
            + "<th style='min-width:30%;width:auto;'><i class='fa'></i>Short Narration</th>"
            + "<th style='min-width:30%;width:auto;'><i class='fa'></i>Delete</th>"
            + "</tr></thead>");
    $("#displayReceiptVoucherAddTable").append("<tbody id='displayReceiptVoucherAddTableBody' class='table-striped table-bordered' />");
}

function journalVoucherValidation() {

    var result = 1;
    var paymentMode = "";
    if ($('#paymentModeRadioButton1').is(':checked')) {
        paymentMode = "Cheque";
    } else if ($('#paymentModeRadioButton2').is(':checked')) {
        paymentMode = "Bank";
    }
    if (paymentMode == "Cheque") {

        if ($("#inFavorOf").val() == "") {
            $("#inFavorOf").focus();
            addSomeClass("inFavorOfFieldGroup", "has-error");
            displaySmallErrorMessages("inFavorOfErr", "Please enter in Favour.");
            result = 0;
        } else if ($("#inFavorOf").val() != "") {
            removeSomeClass("chequeBankNameFieldGroup", "has-error");
        }
        if ($("#chequeAmount").val() == "") {
            $("#chequeAmount").focus();
            addSomeClass("chequeAmountFieldGroup", "has-error");
            displaySmallErrorMessages("chequeAmountErr", "Please enter Cheque Amount.");
            result = 0;
        } else if ($("#chequeAmount").val() != "") {
            if (!$("#chequeAmount").val().match((numbervalidation()))) {
                $("#chequeAmount").focus();
                addSomeClass("chequeAmountFieldGroup", "has-error");
                displaySmallErrorMessages("chequeAmountErr", "Please enter valid cheque amount.");
                result = 0;
            } else {
                $("#chequeAmountErr").text("");
                removeSomeClass("chequeAmountFieldGroup", "has-error");
            }
        }
        if ($("#chequeBankName").val() == "" || $("#chequeBankName").val() == null) {
            $("#chequeBankName").focus();
            addSomeClass("chequeBankNameFieldGroup", "has-error");
            displaySmallErrorMessages("chequeBankNameErr", "Please select Bank.");
            result = 0;
        } else if ($("#chequeBankName").val() != "") {
            removeSomeClass("chequeBankNameFieldGroup", "has-error");
        }
        if ($("#chequeDate").val() == "") {
            $("#chequeDate").focus();
            addSomeClass("chequeDateFieldGroup", "has-error");
            displaySmallErrorMessages("chequeDateErr", "Please enter Cheque Date.");
            result = 0;
        }
        if ($("#chequeNo").val() == "") {
            $("#chequeNo").focus();
            addSomeClass("chequeNoFieldGroup", "has-error");
            displaySmallErrorMessages("chequeNoErr", "Please enter Cheque Number.");
            result = 0;
        } else if ($("#chequeNo").val() != "") {
            if (!$("#chequeNo").val().match((numbervalidation()))) {
                $("#chequeNo").focus();
                addSomeClass("chequeNoFieldGroup", "has-error");
                displaySmallErrorMessages("chequeNoErr", "Please enter valid Cheque Number.");
                result = 0;
            } else {
                $("#chequeNoErr").text("");
                removeSomeClass("chequeNoFieldGroup", "has-error");
            }
        }
    } else if (paymentMode == "Bank") {
        if ($("#bankAmount").val() == "") {
            $("#bankAmount").focus();
            addSomeClass("bankAmountFieldGroup", "has-error");
            displaySmallErrorMessages("bankAmountErr", "Please enter Amount.");
            result = 0;
        } else if ($("#bankAmount").val() != "") {
            if (!$("#bankAmount").val().match((numbervalidation()))) {
                $("#bankAmount").focus();
                addSomeClass("bankAmountFieldGroup", "has-error");
                displaySmallErrorMessages("bankAmountErr", "Please enter valid Amount.");
                result = 0;
            } else {
                $("#bankAmountErr").text("");
                removeSomeClass("bankAmountFieldGroup", "has-error");
            }
        }
        if ($("#bankName").val() == "" || $("#bankName").val() == null) {
            $("#bankName").focus();
            addSomeClass("bankNameFieldGroup", "has-error");
            displaySmallErrorMessages("bankNameErr", "Please select Bank.");
            result = 0;
        } else if ($("#bankName").val() != "" || $("#bankName").val() != null) {
            $("#bankNameErr").text("");
            removeSomeClass("bankAmountFieldGroup", "has-error");
        }
        if ($("#bankAccountNo").val() == "") {
            $("#bankAccountNo").focus();
            addSomeClass("bankAccountNoFieldGroup", "has-error");
            displaySmallErrorMessages("bankAccountNoErr", "Please enter Bank Account Number.");
            result = 0;
        } else if ($("#bankAccountNo").val() != "") {
            if (!$("#bankAccountNo").val().match((numbervalidation()))) {
                $("#bankAccountNo").focus();
                addSomeClass("bankAccountNoFieldGroup", "has-error");
                displaySmallErrorMessages("bankAccountNoErr", "Please enter valid Bank Account Number.");
                result = 0;
            } else {
                $("#bankAccountNoErr").text("");
                removeSomeClass("groupFieldGroup", "has-error");
            }
        }
    }

    if ($("#DDO").val() == null || $("#DDO").val() == "") {
        $("#DDO").focus();
        addSomeClass("ledgerCategoryFieldGroup", "has-error");
        displaySmallErrorMessages("DDOErr", "Please Select DDO.");
        result = 0;
    } else if ($("#DDO").val() != null || $("#DDO").val() != "") {
        $("#DDOErr").text("");
        removeSomeClass("ledgerCategoryFieldGroup", "has-error");
    }
    if ($("#location").val() == null || $("#location").val() == "") {
        $("#location").focus();
        addSomeClass("ledgerCategoryFieldGroup", "has-error");
        displaySmallErrorMessages("locationErr", "Please Select Location.");
        result = 0;
    } else if ($("#location").val() != null || $("#location").val() != "") {
        $("#locationErr").text("");
        removeSomeClass("ledgerCategoryFieldGroup", "has-error");
    }
    if ($("#voucherNumM").val() == null || $("#voucherNumM").val() == "") {
        $("#voucherNumM").focus();
        addSomeClass("ledgerCategoryFieldGroup", "has-error");
        displaySmallErrorMessages("voucherNumMErr", "Please Enter Manual Voucher No.");
        result = 0;
    } else if ($("#voucherNumM").val() != null || $("#voucherNumM").val() != "") {
        $("#voucherNumMErr").text("");
        removeSomeClass("ledgerCategoryFieldGroup", "has-error");
    }
    if ($("#budgetHead").val() == null || $("#budgetHead").val() == "") {
        $("#budgetHead").focus();
        addSomeClass("budgetHeadFieldGroup", "has-error");
        displaySmallErrorMessages("budgetHeadErr", "Please Select Budget Head.");
        result = 0;
    } else if ($("#budgetHead").val() != null || $("#budgetHead").val() != "") {
        $("#budgetHeadErr").text("");
        removeSomeClass("budgetHeadFieldGroup", "has-error");
    }
    if ($("#fundType").val() == null || $("#fundType").val() == "") {
        $("#fundType").focus();
        addSomeClass("fundTypeFieldGroup", "has-error");
        displaySmallErrorMessages("fundTypeErr", "Please Select Fund Type.");
        result = 0;
    } else if ($("#fundType").val() != null || $("#fundType").val() != "") {
        $("#fundTypeErr").text("");
        removeSomeClass("fundTypeFieldGroup", "has-error");
    }
    if ($("#voucherDate").val() == null || $("#voucherDate").val() == "") {
        $("#voucherDate").focus();
        addSomeClass("voucherDateFieldGroup", "has-error");
        displaySmallErrorMessages("voucherDateErr", "Please Enter Voucher Date.");
        result = 0;
    } else if ($("#voucherDate").val() != null || $("#voucherDate").val() != "") {
        $("#voucherDateErr").text("");
        removeSomeClass("voucherDateFieldGroup", "has-error");
    }
    if ($("#ledgerCategory").val() == null || $("#ledgerCategory").val() == "") {
        $("#fundType").focus();
        addSomeClass("fundTypeFieldGroup", "has-error");
        displaySmallErrorMessages("ledgerCategoryErr", "Please Select Ledger Category.");
        result = 0;
    } else if ($("#ledgerCategory").val() != null || $("#ledgerCategory").val() != "") {
        $("#ledgerCategoryErr").text("");
        removeSomeClass("fundTypeFieldGroup", "has-error");
    }

    if ($("#openDiv").val() == 1) {
        if ($("#narrationType").val() == null || $("#narrationType").val() == "" || $("#narrationType").val() == undefined) {

            displaySmallErrorMessages("pregsuccessBefore", "Please fill all mandatory fields.");

            result = 0;
        }
    }
    if (($('#totalDrAmount').val() != $('#totalCrAmount').val()))
    {
        scrolupfunction();
        displayErrorMessages("pregsuccessBefore", " Both Credit and Debit should be same");
        setTimeout(function () {
            $("#pregsuccessBefore").focus();
            $("#pregsuccessBefore").text("");

        }, 3000);
        result = 0;
    } else if (($('#totalDrAmount').val() == $('#totalCrAmount').val())) {

        $('#Savebuttonmsg').text("").val("");
        removeSomeClass("fundTypeFieldGroup", "has-error");
    }

    $('table#displayReceiptVoucherAddTable tbody tr').each(function () {
        if ($(this).find('td:eq(2) select[name="group"]').val() == undefined || $(this).find('td:eq(2) select[name="group"]').val() == "" || $(this).find('td:eq(2) select[name="group"]').val() == null || $(this).find('td:eq(2) select[name="ledger"]').val() == undefined || $(this).find('td:eq(2) select[name="ledger"]').val() == "" || $(this).find('td:eq(2) select[name="ledger"]').val() == null) {
            result = 2;
        }

    });

    $('table#displayReceiptVoucherAddTable tbody tr').each(function () {
        if ($(this).find('td:eq(1) select ').val() == "" || $(this).find('td:eq(1) select ').val() == undefined || $(this).find('td:eq(1) select ').val() == null) {
            result = 2;
        }
    });

    $('table#displayReceiptVoucherAddTable tbody tr').each(function () {
        var drcr = $(this).find('td:eq(1) select ').val();
        if (drcr == "Dr") {
            if ($(this).find('td:eq(3) input').val() == undefined || $(this).find('td:eq(3) input').val() == "" || $(this).find('td:eq(3) input').val() == null) {
                result = 2;
            }
        } else if (drcr == "Cr") {
            if ($(this).find('td:eq(4) input').val() == undefined || $(this).find('td:eq(4) input').val() == "" || $(this).find('td:eq(3) input').val() == null) {
                result = 2;
            }
        }
    });


    if (result == 1) {

        if ($("#saveorupdate").val() == "save") {
            saveJournalVoucherDetails();
        } else if ($("#saveorupdate").val() == "update") {
            updateJournalVoucherDetails();
        }
    } else if (result == 5) {
        displayErrorMessages("pregsuccessBefore", "Please fill ledger amount details", "");
        setTimeout(function () {
            $("#pregsuccessBefore").text("");
        }, 1500);
    } else if (result == 2) {
        displayErrorMessages("pregsuccessBefore", "Please fill all mandatory fields", "");
        setTimeout(function () {
            $("#pregsuccessBefore").text("");
        }, 1500);
    } else if (result == 3) {
        displayErrorMessages("pregsuccessBefore", "Please enter Debit(Dr) Amount", "");
        setTimeout(function () {
            $("#pregsuccessBefore").text("");
        }, 1500);
    } else if (result == 4) {
        displayErrorMessages("pregsuccessBefore", "Please enter Credit(Cr) Amount", "");
        setTimeout(function () {
            $("#pregsuccessBefore").text("");
        }, 1500);
    }
}
function getRowsLengthForJournalVoucher() {
    var HowManyRows = 0;
    $('table#displayReceiptVoucherAddTable tbody tr').each(function () {
        HowManyRows++;
    });
    return HowManyRows;
}
function getLocationBasedOnDDOInJournalVoucher(name, ddoId) {
    var ddo = $("#DDO").val();

    if (ddo == null)
    {
        ddo = ddoId
    }
    $.get(server_base_url + "hrms/employee/Employee/GetDropDownValues", {
        ddo: ddo,
        condition: getLocationBasedOnDdo
    }).done(function (pdata) {

        if (pdata != "500" && pdata != 500 && pdata != "" && pdata != null)
        {
            $("#location").text("").append("<option value = '' selected>---- Select Location ----</option>");
            for (var k = 0; k < pdata.length; k++) {
                if (name == pdata[k]._id.$oid)
                {
                    $("#location").append("<option  value='" + pdata[k]._id.$oid + "' selected>" + pdata[k].locationName + "</option>");
                } else
                {
                    $("#location").append("<option  value='" + pdata[k]._id.$oid + "' >" + pdata[k].locationName + "</option>");
                }
            }
        } else
        {
            $("#location").text("").append("<option value = '' selected>---- No Data Available ----</option>");
        }
    });
}
function saveJournalVoucherDetails() {
    if (checkUserPrivelege(pvCreateJournalVoucher)) {

        var ledgerList = [];
        $('table#displayReceiptVoucherAddTable tbody tr').each(function () {
            ledgerList.push({
                DrCr: $(this).find('td:eq(1) select ').val(),
                group: $(this).find('td:eq(2) select[name="group"]').val(),
                groupName: $(this).find('td:eq(2) select[name="group"] option:selected').text(),
                ledger: $(this).find('td:eq(2) select[name="ledger"]').val(),
                ledgerName: $(this).find('td:eq(2) select[name="ledger"] option:selected').text(),
                drAmount: $(this).find('td:eq(3) input').val(),
                crAmount: $(this).find('td:eq(4) input').val(),
                shortNarration: $(this).find('td:eq(5) input ').val()
            });
        });


        var paymentMode = "";
        if ($('#paymentModeRadioButton1').is(':checked')) {
            paymentMode = "Cheque";
        } else if ($('#paymentModeRadioButton2').is(':checked')) {
            paymentMode = "Bank";
        } else {
            paymentMode = "None";
        }

        var JournalVoucherJson = {
            manualVoucher: $("#voucherNumM").val(),
            narrationType: $("#narrationType").val(),
            DDO: $("#DDO").val(),
            location: $("#location").val(),
            voucherNo: $("#voucherNo").val(),
            voucherDate: $("#voucherDate").val(),
            fundType: $("#fundType").val(),
            budgetHead: $("#budgetHead").val(),
            ledgerCategory: $("#ledgerCategory").val(),
            totalDrAmount: $("#totalDrAmount").val(),
            totalCrAmount: $("#totalCrAmount").val(),
            narration: $("#narration").val(),
            ledgerList: ledgerList,
            chequeNo: $("#chequeNo").val(),
            chequeDate: $("#chequeDate").val(),
            chequeBankName: $("#chequeBankName").val(),
            chequeAmount: $("#chequeAmount").val(),
            inFavorOf: $("#inFavorOf").val(),
            chequeRemarks: $("#chequeRemarks").val(),
            bankAccountNo: $("#bankAccountNo").val(),
            bankName: $("#bankName").val(),
            bankAmount: $("#bankAmount").val(),
            bankRemarks: $("#bankRemarks").val(),
            paymentMode: paymentMode

        }

        $.post(server_base_url + "/financial/transaction/JournalVoucher/Save", {
            journalVoucherJson: JSON.stringify(JournalVoucherJson),
            userid: getUserSessionElement("userId"),
            ddoId: $("#DDO").val(),
            locationId: $("#location").val(),
        }).done(function (data) {

            if (data == fail) {
                displaySmallErrorMessages("pregsuccessBefore", "Invalid username / password" + "<br/><br/>");
            } else if (data == unauthorized || data.statuscode == unauthorized) {
                displaySmallErrorMessages("pregsuccessBefore", unauthorizedMessage + "<br/><br/>");
            } else if (data == statusException) {
                displaySmallErrorMessages("pregsuccessBefore", statusExceptionMessage + "<br/><br/>");
            } else if (data == invalidSession) {
                callSessionTimeout();
            } else if (data == null) {
                displaySmallErrorMessages("pregsuccessBefore", "No User available" + "<br/><br/>");
            } else {
                scrolupfunction();
                displaySuccessMessages("pregsuccessBefore", successMessage, "");
                setTimeout(function () {
                    journalVoucherMaster1("dashBoardBodyMainDiv");
                }, 1500);
            }
        });
    }
}
function validate(key)
{
//getting key code of pressed key
    var keycode = (key.which) ? key.which : key.keyCode;
    //comparing pressed keycodes
    if (!(keycode == 8 || keycode == 12) && (keycode < 13 || keycode > 13) && (keycode < 48 || keycode > 57))
    {
        return false;
    } else {
        return true;
    }
}
//Function to allow only alpha numeric to textbox
function validatealphanumeric(key) {

    var keycode = (key.which) ? key.which : key.keyCode;
//comparing pressed keycodes
    if (!(keycode == 8 || keycode == 12) && (keycode < 13 || keycode > 13) && (keycode < 32 || keycode > 33) && (keycode < 65 || keycode > 90) && (keycode < 97 || keycode > 122)) {

        return false;
    } else {

        return true;
    }
}

function fetchLedgerCategoryForJournalVoucher(name, DivId, message) {
    $.get(server_base_url + "financial/common/LedgerCategory/ListForOptions", {
    }).done(function (bpdata) {
        bpdata = JSON.parse(bpdata);
        if (bpdata != null) {
            $("#" + DivId).append("<option value='' selected disabled>---- Select " + message + "----</option>");
            if (bpdata.length > 0) {
                for (var i = 0; i < bpdata.length; i++) {
                    if (name == bpdata[i].ledgerCategory) {
                        $("#" + DivId).append("<option  value='" + bpdata[i] + "' selected>" + bpdata[i] + "</option>");
                    } else {
                        $("#" + DivId).append("<option  value='" + bpdata[i] + "' >" + bpdata[i] + "</option>");
                    }
//                    $("#" + DivId).append("<option  value='" + bpdata[i].ledgerCategory + "' >" + bpdata[i].ledgerCategory + "</option>");
                }
            }
        }
    });
}
function getGroupListForOptionsJournal(name, DivId, message, drcrId) {

    $.get(server_base_url + "/financial/account/GroupMaster/ViewList", {
    }).done(function (data) {
        if (data != null) {

            var sno = 0;
            var mainData = data.result;
            $("#" + DivId).text("");
            $("#" + DivId).append("<option value='' selected disabled>---- Select " + message + "----</option>");

            for (var i = mainData.length - 1; i >= 0; i--) {

                var subData = mainData[i];

                if (name == subData._id.$oid) {
                    $("#" + DivId).append("<option  value='" + subData._id.$oid + "' selected>" + subData.groupName + "</option>");
                } else {
                    if ($("#" + drcrId).val() == "Dr")
                    {

                        if (subData.groupName != "Cash Group" && subData.groupName != "Bank Group")
                        {
                            $("#" + DivId).append("<option value='" + subData._id.$oid + "' >" + subData.groupName + "</option>");
                        }

                    } else if ($("#" + drcrId).val() == "Cr")
                    {
                        if (subData.groupName != "Cash Group" && subData.groupName != "Bank Group")
                        {
                            $("#" + DivId).append("<option value='" + subData._id.$oid + "'>" + subData.groupName + "</option>");
                        }
                    }
                }
            }
        }
    });
}

function viewJournalVoucherListMaster(DivId) {
    if (checkUserPrivelege(pvViewJournalVoucher)) {
        $("#" + DivId).text("").append("<div class='tab-pane' id='viewUser'/>");
        $("#viewUser").append("<div class='table-responsive' id='viewUserSectionTableDiv' />");
        $("#viewUserSectionTableDiv").append("<table class='table table-bordered table-warning mb30' id='displayBankTable' />");
        $("#displayBankTable").append("<thead class=''><tr id='displayBankTabletrHeadJV'>"

                + " <th> S.No</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Voucher Number</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Fund Type</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Total Dr Amount</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Total Cr Amount</th>");
        if (checkUserPrivelege(pvUpdateJournalVoucher)) {
            $("#displayBankTabletrHeadJV").append("<th style='min-width:1%;width:80px;''><i class='fa'></i>Edit</th>");
        }
        //   + "<th style='min-width:1%;width:80px;''><i class='fa' style='font-size:21px;'></i> Delete</th>"
//                + "</tr></thead>");

        var ddoLocationMap = {DDO: $("#DDO").val(), location: $("#location").val()};

        $.get(server_base_url + "/financial/transaction/JournalVoucher/ViewList", {
            filter: JSON.stringify(ddoLocationMap)}).done(function (bdata) {

            if (bdata == fail) {
                $("#ErrorMessageDiv1").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>No Data Available..<strong></div></center>");
//            displayLargeErrorMessages("pregsuccessBefore", "" + failMessage + "<br /><br />");
//            displayLargeErrorMessages("pregsuccessAfter", "" + failMessage + "<br /><br />");
            } else if (bdata == unauthorized || bdata.statuscode == unauthorized) {
                $("#ErrorMessageDiv1").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>No Data Available..<strong></div></center>");
            } else if (bdata == invalidSession) {
                callSessionTimeout();
            } else if (bdata == statusException) {
                $("#ErrorMessageDiv1").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>No Data Available..<strong></div></center>");
            } else {
                if (bdata != null) {
                    if (bdata.length > 0) {
                        var sno = 0;
                        $("#displayBankTable").append("<tbody id='displayBankTableBody' class='' />");
//                    for (var i = 0; i < bdata.length; i++) {
                        for (var i = bdata.length - 1; i >= 0; i--) {
                            sno++;
                            var objjson = {
                                objId: bdata[i]._id.$oid,
                                voucherNo: bdata[i].voucherNo,
                                DDO: bdata[i].DDO,
                                narrationType: bdata[i].narrationType,
                                location: bdata[i].location,
                                manualVoucher: bdata[i].manualVoucher,
                                voucherDate: bdata[i].voucherDate,
                                fundType: bdata[i].fundType,
                                budgetHead: bdata[i].budgetHead,
                                ledgerCategory: bdata[i].ledgerCategory,
                                isGrant: bdata[i].isGrant,
                                ledgerList: bdata[i].ledgerList,
                                totalDrAmount: bdata[i].totalDrAmount,
                                totalCrAmount: bdata[i].totalCrAmount,
                                narration: bdata[i].narration,
                                paymentMode: bdata[i].paymentMode,
                                chequeNo: bdata[i].chequeNo,
                                chequeDate: bdata[i].chequeDate,
                                chequeBankName: bdata[i].chequeBankName,
                                chequeAmount: bdata[i].chequeAmount,
                                inFavorOf: bdata[i].inFavorOf,
                                chequeRemarks: bdata[i].chequeRemarks,
                                bankAccountNo: bdata[i].bankAccountNo,
                                bankName: bdata[i].bankName,
                                bankAmount: bdata[i].bankAmount,
                                bankRemarks: bdata[i].bankRemarks,
                                postingStatus: bdata[i].postingStatus
                            };
                            objjson = JSON.stringify(objjson);
                            $("#displayBankTableBody").append("<tr id='" + bdata[i]._id.$oid + "' style='cursor:pointer;' >"
                                    + "<td>" + sno + "</td>"
                                    + "<td style='cursor:pointer;'>" + bdata[i].voucherNo + "</td>"
                                    + "<td style='cursor:pointer;'>" + bdata[i].fundType + "</td>"
                                    + "<td style='cursor:pointer;'>" + bdata[i].totalDrAmount + "</td>"
                                    + "<td style='cursor:pointer;'>" + bdata[i].totalCrAmount + "</td>");
                            if (checkUserPrivelege(pvUpdateJournalVoucher)) {
                                $("#" + bdata[i]._id.$oid).append("<td style='cursor:pointer;' onclick=updateJournalVoucher('" + encodeURI(objjson) + "')>" + ' <i class="fa fa-edit"></i>&nbsp;&nbsp;<a  class="anchor_edit">Edit</a>' + "</td>");

                            }
                            //   + "<td style='cursor:pointer;' onclick=updateJournalVoucher('" + encodeURI(objjson) + "')>" + ' <button type="button"  class="btn btn-primary mr5"style="align:center;color:white"  >EDIT</button>' + "</td>"
                            //  + "<td onclick=deleteJournalVoucher('" + bdata[i]._id.$oid + "')>" + ' <button type="button" class="btn btn-danger mr5"  style="align:center;color:white" >DELETE</button>' + "</td></tr>");
                        }
                        $('#displayBankTable').dataTable();
                    }
                } else {
                    $("#ErrorMessageDiv1").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>No Data Available..<strong></div></center>");
                }
            }
        });
    }
}
function deleteJournalVoucher(objId) {
    if (checkUserPrivelege(pvDeleteJournalVoucher)) {


        $.post(server_base_url + "/financial/transaction/JournalVoucher/Delete", {
            jvId: objId,
            userid: getUserSessionElement("userId")
        }).done(function (data) {
            if (data == fail) {
                displaySmallErrorMessages("pregsuccessBefore", "Invalid username / password");
            } else if (data == unauthorized || data.statuscode == unauthorized) {
                displaySmallErrorMessages("pregsuccessBefore", unauthorizedMessage);
            } else if (data == statusException) {
                displaySmallErrorMessages("pregsuccessBefore", statusExceptionMessage);
            } else if (data == invalidSession) {
                callSessionTimeout();
            } else if (data == null) {
                displaySmallErrorMessages("pregsuccessBefore", "No User available");
            } else {

                scrolupfunction();
                displaySuccessMessages("pregsuccessBefore", deleteSuccessMessage, "");
                setTimeout(function () {
                    journalVoucherMaster1("dashBoardBodyMainDiv");
                }, 1500);
            }
        });
    }
}

function  updateJournalVoucher(obj) {
    if (checkUserPrivelege(pvUpdateJournalVoucher)) {
        var numberofRows = 0;
        obj = decodeURI(obj);
        obj = JSON.parse(obj);
        viewJournalVoucherAddList('receiptVoucherlistAddpanelRow');
        addJournalVoucherRows("displayReceiptVoucherAddTableBody", obj.ledgerList);


        $("#FieldGroup").append("<input type='hidden' id='saveorupdate' value='update'>");
        $("#FieldGroup").append("<input type='hidden' id='objId' value='" + obj.objId + "'>");
        $("#saveorupdate").val("update");
        $("#voucherDate").val(obj.voucherDate);
        $("#voucherNo").val(obj.voucherNo);
        $("#voucherNumM").val(obj.manualVoucher);

        $("#displayBankTableBody tr").css("background-color", "white");
        $("#displayBankTableBody tr" + "#" + obj.objId).css("background-color", "rgba(10, 129, 156, 0.3)");
        setTimeout(function () {
            fetchLedgerCategoryForJournalVoucher(obj.ledgerCategory);
            $("#ledgerCategory option:contains(" + obj.ledgerCategory + ")").attr('selected', 'selected');
        }, 5000);

        // $("#panelRow4").text("").append("<div class='col-sm-6'><button type='button'   class='btn btn-success pull-right mr5'  onclick=addJournalVoucherRows('displayReceiptVoucherAddTableBody')>Add</button></div>");

        // $("#panelRowNarrationbutton").text("").append("<div  class='col-xs-3 ' /><div class='col-xs-1'><button type='button' style='margin-left:10px' value='Add' class='btn btn-success pull-right narration' >Show Narrations</button></div>");

        // setTimeout(function () {
        $("#narration").val(obj.narration);
        getNarrationListinJournal(obj.narrationType);
        //   $("#openDiv").val('1');
        $("#narrationType option:contains(" + obj.narrationType + ")").attr('selected', 'selected');
        // }, 400);



        //   getNarrationListinJournal(obj.narrationType);

//    if (obj.narrationType != null && obj.narrationType != undefined)
//    {
//        $(".narrationval").toggle();
//    }

        $("#panelMainBody").append("<br><div id='panelRow5' class='row' />");
        $("#panelRow5").text("").append("<div  class='col-xs-3' /><div class='col-xs-3'><button type='button' style='margin-left:10px' value='Save' class='btn btn-success mr5 pull-right' onclick='journalVoucherValidation()'>Update</button></div><div class='col-xs-2'><button type='button' onclick=journalVoucherMaster1('dashBoardBodyMainDiv') class='btn btn-warning mr5 pull-left' name='reset' value='reset'>Back</button></div><div class='col-xs-2'><button type='button' style='margin-left:10px' value='Delete' class='btn btn-danger mr5' onclick=deletePopUp('deleteJournalVoucher','updateJournalVoucher','" + obj.objId + "')>Delete</button></div>");
        $("#panelRow5").append("<div  class='col-xs-3' id='Savebuttonmsg' />");

        setTimeout(function () {
            viewOptionIdName("budget/master/FundType/View", obj.fundType, "description", "fundType", "Fund Type");
        }, 400);
        setTimeout(function () {
            getDDOforJournalVoucher(obj.DDO, "DDO");
        }, 400);
        setTimeout(function () {
            getLocationBasedOnDDOInJournalVoucher(obj.location, obj.DDO);
        }, 4000);
        setTimeout(function () {
            viewOptionsInUpdateforBudgetHead("hrms/common/BudgetHead/View", obj.budgetHead, "budgetHead", "budgetHead", "Budget Head");
        }, 400);



        $("#totalCrAmount").val(obj.totalCrAmount);
        $("#totalDrAmount").val(obj.totalDrAmount);

        if (obj.paymentMode == "Bank") {
            setTimeout(function () {
                addBankDetailRowJournal("panelRowPaymentModeDivision1", obj.bankAccountNo, obj.bankName, obj.bankAmount, obj.bankRemarks);
            }, 100);
        } else if (obj.paymentMode == "Cheque") {
            setTimeout(function () {
                addChequeDetailRowJournal("panelRowPaymentModeDivision1", obj.chequeNo, obj.chequeDate, obj.chequeBankName, obj.chequeAmount, obj.inFavorOf, obj.chequeRemarks);
            }, 100);
        }
    }
}

function updateJournalVoucherDetails() {
    if (checkUserPrivelege(pvUpdateJournalVoucher)) {
        var rvId = $("#objId").val();
        var ledgerList = [];
        $('table#displayReceiptVoucherAddTable tbody tr').each(function () {
            ledgerList.push({
                DrCr: $(this).find('td:eq(1) select ').val(),
                group: $(this).find('td:eq(2) select[name="group"]').val(),
                groupName: $(this).find('td:eq(2) select[name="group"] option:selected').text(),
                ledger: $(this).find('td:eq(2) select[name="ledger"]').val(),
                ledgerName: $(this).find('td:eq(2) select[name="ledger"] option:selected').text(),
                drAmount: $(this).find('td:eq(3) input').val(),
                crAmount: $(this).find('td:eq(4) input').val(),
                shortNarration: $(this).find('td:eq(5) input ').val()
            });
        });
        var paymentMode = "";
        if ($('#paymentModeRadioButton1').is(':checked')) {
            paymentMode = "Cheque";
        } else if ($('#paymentModeRadioButton2').is(':checked')) {
            paymentMode = "Bank";
        } else {
            paymentMode = "No";
        }

        var JournalVoucherJson = {
            manualVoucher: $("#voucherNumM").val(),
            narrationType: $("#narrationType").val(),
            DDO: $("#DDO").val(),
            location: $("#location").val(),
            voucherNo: $("#voucherNo").val(),
            voucherDate: $("#voucherDate").val(),
            fundType: $("#fundType").val(),
            budgetHead: $("#budgetHead").val(),
            ledgerCategory: $("#ledgerCategory").val(),
            totalDrAmount: $("#totalDrAmount").val(),
            totalCrAmount: $("#totalCrAmount").val(),
            narration: $("#narration").val(),
            ledgerList: ledgerList,
            chequeNo: $("#chequeNo").val(),
            chequeDate: $("#chequeDate").val(),
            chequeBankName: $("#chequeBankName").val(),
            chequeAmount: $("#chequeAmount").val(),
            inFavorOf: $("#inFavorOf").val(),
            chequeRemarks: $("#chequeRemarks").val(),
            bankAccountNo: $("#bankAccountNo").val(),
            bankName: $("#bankName").val(),
            bankAmount: $("#bankAmount").val(),
            bankRemarks: $("#bankRemarks").val(),
            paymentMode: paymentMode,
            postingStatus: "new"
        };
        $.post(server_base_url + "/financial/transaction/JournalVoucher/Update", {
            journalVoucherJson: JSON.stringify(JournalVoucherJson),
            userid: getUserSessionElement("userId"),
            jvId: rvId
        }).done(function (data) {

            if (data == fail) {
                displaySmallErrorMessages("pregsuccessBefore", "Invalid username / password" + "<br/><br/>");
            } else if (data == unauthorized || data.statuscode == unauthorized) {
                displaySmallErrorMessages("pregsuccessBefore", unauthorizedMessage + "<br/><br/>");
            } else if (data == statusException) {
                displaySmallErrorMessages("pregsuccessBefore", statusExceptionMessage + "<br/><br/>");
            } else if (data == invalidSession) {
                callSessionTimeout();
            } else if (data == null) {
                displaySmallErrorMessages("pregsuccessBefore", "No User available" + "<br/><br/>");
            } else {

                scrolupfunction();
                displaySuccessMessages("pregsuccessBefore", updateSuccessMessage, "");
                setTimeout(function () {
                    journalVoucherMaster1("dashBoardBodyMainDiv");
                }, 1500);
            }
        });
    }
}

function getFinancialFundTypeOptionsForJournalVoucher(name, DivId, message)
{
    $.get(server_base_url + "financial/common/FundType/ViewList", {
    }).done(function (bdata) {
//        bdata=JSON.parse(bdata);
        if (bdata != null) {
            $("#" + DivId).append("<option value = '' selected disabled>---- Select " + message + " ----</option>");
            if (bdata.length > 0) {
                for (var i = 0; i < bdata.length; i++) {
                    if (name == bdata[i].description) {
                        $("#" + DivId).append("<option  value='" + bdata[i].description + "' selected>" + bdata[i].description + "</option>");
                    } else {
                        $("#" + DivId).append("<option  value='" + bdata[i].description + "' >" + bdata[i].description + "</option>");
                    }
                }
            }
        }
    });
}
function SearchJournalVoucher() {
    if (checkUserPrivelege(pvViewJournalVoucher)) {
        $("#tableHeader").append("<div id='searchListPanel' class='panel panel-blue' />");
        $("#searchListPanel").append("<div id='searchListPanelHeading' class='panel-heading' />");
        $("#searchListPanelHeading").append("<h4 id='SearchfirstHeader' class='panel-title' />");
        $("#SearchfirstHeader").append("<div class='panel-title' a data-toggle='collapse' style='font-weight:bold;font-size:15px;' data-parent='#accordion2' href='#collapseOne4' ><center>Search Journal Voucher</center><div class='pull-right' style='position: relative;bottom: 15px;cursor:pointer;' id='searchJournalVoucherColDiv'><span class='glyphicon glyphicon-minus-sign'></span></div></div>");
        $("#searchListPanel").append("<div id='collapseOne4' class='panel-collapse collapse in' />");
        $("#searchJournalVoucherColDiv").click(function () {
            $("#collapseOne4").toggle();
            if ($("#searchJournalVoucherColDiv span").hasClass("glyphicon-minus-sign")) {
                $("#searchJournalVoucherColDiv").text("").append("<span class='glyphicon glyphicon-plus-sign'></span>");
            } else {
                $("#searchJournalVoucherColDiv").text("").append("<span class='glyphicon glyphicon-minus-sign'></span>");
            }
        });
        $("#collapseOne4").append("<div id='searchlistpanelMainBody' class = 'panel-body' />");

        $("#searchlistpanelMainBody").append("<div id='searchpanelRow' class='row' />");
        $("#searchpanelRow").append("<div id='SearchErrorMessageDiv'  />");
        //Row 1
        $("#searchpanelRow").append("<div id='searchRow1' class='row' />");
        $("#searchRow1").append("<div id='SearchGroup1' class='form-group' />");

        $("#SearchGroup1").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="">From Date <span class="require">*</span> </label><input type="text" id="SearchFromDate" class="form-control">'
                + '</div><div class="form-group col-lg-6"><label for="location">To Date <span class="require">*</span> <span id="toDateErr"></span></label><input type="text"   id="SearchToDate"  class="form-control"></div></div>');

        $("#SearchGroup1").append('<div class="col-lg-12"><div class="form-group col-lg-6" id="FieldDiv2"><label for="fundtype">Fund Type  </label><select class="form-control" name="fundType" id="fundType1"></select>'
                + '</div><div class="form-group col-lg-6" id="FieldDiv3"><label for="location">Budget Head  </label><select class="form-control" id="budgetHead1"></select></div></div>');
        $("#SearchGroup1").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label> Voucher No.  </label><input type ="text" id="searchVoucherNo" class="form-control">'
                + '</div><div class="form-group col-lg-6" id="FieldDiv3"><label for="location">Ledger Category  </label><select class="form-control" id="ledgerCategory1"></select></div></div>');

        $("#SearchDiv1").append("<span id='SearchFromDateErr'></span>");
        $("#SearchDiv2").append("<span id='SearchToDateErr'></span>");

        $("#SearchDiv3").append("<span id='searchVoucherNoErr'></span>");
        $('#SearchFromDate').datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd-mm-yy",
            yearRange: '-50:+50',
            onSelect: function (date) {
                var date1 = $('#SearchFromDate').datepicker('getDate');
                var date = new Date(Date.parse(date1));
                date.setDate(date.getDate() + 1);
                var newDate = date.toDateString();
                newDate = new Date(Date.parse(newDate));
                $('#SearchToDate').datepicker("option", "minDate", newDate);
            }
        });
        $('#SearchToDate').datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd-mm-yy",
            yearRange: '-50:+50',
            minDate: $("#SearchFromDate").datepicker("getDate")
        });
        $("#SearchFromDate").keypress(function (event) {
            event.preventDefault();
        });
        $("#SearchToDate").keypress(function (event) {
            event.preventDefault();
        });

        setTimeout(function () {
            viewOption("hrms/common/BudgetHead/View", "", "budgetHead", "budgetHead1", "Budget Head");
        }, 300);

        setTimeout(function () {
            viewOptionIdName("budget/master/FundType/View", "", "description", "fundType1", "Fund Type");
        }, 200);
        setTimeout(function () {
            fetchLedgerCategoryForReceiptVoucher("", "ledgerCategory1", "Ledger Category");
        }, 400);

        $("#searchpanelRow").append("<br><div id='searchRow3' class='row' />");

        $("#searchRow3").append("<div  class='col-xs-3' /><div class='col-xs-3'><button type='button' style='margin-left:10px' value='Save' class='btn btn-success mr5 pull-right' onclick='searchJournalVoucherFunction()'>Search</button></div><div class='col-xs-2'><button type='button' onclick=resetAllValuesInSpecifiedDiv('searchlistpanelMainBody') class='btn btn-warning mr5 pull-left' name='reset' value='reset'>Reset</button></div>");

        //    $("#searchRow2").append("<center><button  onclick='searchJournalVoucherFunction()' class='btn btn - success' style='height:40px; width:80px'>Search</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button onclick='resetSearchJournalVoucherFunctionDeatils()' class='btn btn - warning'  style='height:40px; width:80px'>Reset</button></center>");
    }
}

function searchJournalVoucherFunction() {
    if (checkUserPrivelege(pvViewJournalVoucher)) {
        var fromDate = $("#SearchFromDate").val();
        var ToDate = $("#SearchToDate").val();
        var voucherNo = $("#searchVoucherNo").val();
        var voucherNoLength = voucherNo.length;
        var result = 1;
        var days = checkFromDateAndToDate();
        if (days < 0) {
            $("#SearchToDate").focus();
            displaySmallErrorMessagesInRed("toDateErr", "To Date should be greater than or equal to From Date ");
            result = 0;
        } else {
            $("#toDateErr").text("");
            $("#SearchToDateErr").text("");
            $("#SearchFromDateErr").text("");
            $("#searchVoucherNoErr").text("");
            $("#SearchErrorMessageDiv").text("");
            $("#ErrorMessageDiv1").text("");

            if (fromDate.length == 0 && ToDate.length == 0 && voucherNo.length == 0) {
                $("#SearchErrorMessageDiv").text("").append("<center><div class='col-sm-12' style='color:red;'><strong>Please fill the  Mandatory fields<strong></div></center><br>");
                return;
            }
            var fromDateLength = fromDate.length;
            var ToDateLength = ToDate.length;
            if (fromDateLength > 0) {
                if (ToDateLength == 0) {
                    $("#SearchToDateErr").text("").append("Please Enter To Date");
                    $("#SearchToDate").focus();
                    return;
                }
            }
            if (ToDateLength > 0) {
                if (fromDateLength == 0) {
                    $("#SearchFromDateErr").text("").append("Please Enter From Date");
                    $("#SearchFromDate").focus();
                    return;
                }
            }

//    if (compareTwoDates("SearchFromDate", "SearchToDate") === 1) {
//        return;
//    }

            var ddoLocationMap = {DDO: $("#DDO").val(), location: $("#location").val()};

            $.post(server_base_url + "/financial/transaction/JournalVoucher/Search", {
                fromDate: fromDate,
                ToDate: ToDate,
                voucherNo: voucherNo,
                filter: JSON.stringify(ddoLocationMap)
            }).done(function (bdata) {

                if (bdata != null) {
                    //
                    $("#listpanelRow").text("").append("<div class='tab-pane' id='viewUser'/>");
                    $("#viewUser").append("<div class='table-responsive' id='viewUserSectionTableDiv' />");
                    $("#viewUserSectionTableDiv").append("<table class='table table-bordered table-striped table-warning mb30' id='displayBankTable' />");
                    $("#displayBankTable").append("<thead class=''><tr id='displayBankTableTrHeadJV'>"

                            + " <th> S.No</th>"
                            + "<th style='min-width:30%;width:auto;'><i ></i>Voucher Number</th>"
                            + "<th style='min-width:30%;width:auto;'><i ></i>Fund Type</th>"
                            + "<th style='min-width:30%;width:auto;'><i ></i>Total Dr Amount</th>"
                            + "<th style='min-width:30%;width:auto;'><i ></i>Total Cr Amount</th>"
                            + "<th style='min-width:30%;width:auto;'><i ></i>Payment Mode</th>");
                    if (checkUserPrivelege(pvUpdateJournalVoucher)) {
                        $("#displayBankTableTrHeadJV").append("<th style='min-width:1%;width:80px;''><i class='fa'></i>Edit</th>");
                    }
                    //   + "<th style='min-width:1%;width:80px;''><i class='fa' style='font-size:21px;'></i> Delete</th>"
//                            + "</tr></thead>");
                    //
//            viewJournalVoucherListMaster('listpanelRow');
                    if (bdata != "") {
                        if (bdata.length > 0) {
                            var sno = 0;
                            $("#displayBankTable").append("<tbody id='displayBankTableBody' class='table-striped table-bordered' />");
//                    for (var i = 0; i < bdata.length; i++) {
                            for (var i = bdata.length - 1; i >= 0; i--) {
                                var obj = bdata[i].value;
                                sno++;
                                var objjson = {
                                    objId: obj._id,
                                    voucherNo: obj.voucherNo,
                                    DDO: obj.DDO,
                                    narrationType: obj.narrationType,
                                    location: obj.location,
                                    manualVoucher: obj.manualVoucher,
                                    voucherDate: obj.voucherDate,
                                    fundType: obj.fundType,
                                    budgetHead: obj.budgetHead,
                                    ledgerCategory: obj.ledgerCategory,
                                    isGrant: obj.isGrant,
                                    ledgerList: obj.ledgerList,
                                    totalDrAmount: obj.totalDrAmount,
                                    totalCrAmount: obj.totalCrAmount,
                                    narration: obj.narration,
                                    paymentMode: obj.paymentMode,
                                    chequeNo: obj.chequeNo,
                                    chequeDate: obj.chequeDate,
                                    chequeBankName: obj.chequeBankName,
                                    chequeAmount: obj.chequeAmount,
                                    inFavorOf: obj.inFavorOf,
                                    chequeRemarks: obj.chequeRemarks,
                                    bankAccountNo: obj.bankAccountNo,
                                    bankName: obj.bankName,
                                    bankAmount: obj.bankAmount,
                                    bankRemarks: obj.bankRemarks,
                                    postingStatus: obj.postingStatus
                                }
                                objjson = JSON.stringify(objjson);
                                $("#displayBankTableBody").append("<tr id='" + sno + "' style='cursor:pointer;' >"
                                        + "<td>" + sno + "</td>"
                                        + "<td style='cursor:pointer;'>" + obj.voucherNo + "</td>"
                                        + "<td style='cursor:pointer;'>" + obj.fundType + "</td>"
                                        + "<td style='cursor:pointer;'>" + obj.totalDrAmount + "</td>"
                                        + "<td style='cursor:pointer;'>" + obj.totalCrAmount + "</td>"
                                        + "<td style='cursor:pointer;'>" + obj.paymentMode + "</td>");
                                if (checkUserPrivelege(pvUpdateJournalVoucher)) {
                                    $("#" + sno).append("<td style='cursor:pointer;' onclick=updateJournalVoucher('" + encodeURI(objjson) + "')>" + ' <i class="fa fa-edit"></i>&nbsp;&nbsp;<a  class="anchor_edit">Edit</a>' + "</td>");
                                }
                                // + "<td onclick=deleteJournalVoucher('" + obj._id + "')>" + ' <button type="button" class="btn btn-danger mr5"  style="align:center;color:white" >DELETE</button>' + "</td></tr>");
                            }
                            $('#displayBankTable').dataTable();
                        }
                    } else {
                        $("#ErrorMessageDiv1").text("").append("<center><div class='col-sm-12' style='color:red;'><strong>No data Available.<strong></div></center><br>");
                    }
                }
            });
        }
    }
}

function getDDOforJournalVoucher(name, DivId)
{
    $.get(server_base_url + "financial/common/DDOListForOptions", {
    }).done(function (pdata) {
        if (pdata != null) {
            $("#" + DivId).text("").append("<option value='' selected>---- Select DDO ----</option>");
            if (pdata.length > 0) {
                for (var i = 0; i < pdata.length; i++) {
                    if (name == pdata[i]._id.$oid) {
                        $("#" + DivId).append("<option  value='" + pdata[i]._id.$oid + "' selected>" + pdata[i].ddoName + "</option>");
                    } else {
                        $("#" + DivId).append("<option  value='" + pdata[i]._id.$oid + "' >" + pdata[i].ddoName + "</option>");
                    }
                }
            }
        }
    });
}
function getHardCodedOptionsJournalVoucher(name, DivId) {
    var DrCrOptions = ["Dr", "Cr"];
    $("#" + DivId).text("").append("<option value='' selected >---- Select  ----</option>");
    for (var i = 0; i < DrCrOptions.length; i++) {
        $("#" + DivId).append("<option  value='" + DrCrOptions[i] + "' >" + DrCrOptions[i] + "</option>");
    }
    $("#" + DivId).val(name);
}
function checkFromDateAndToDate() {
    var fDate = $("#SearchFromDate").datepicker("getDate");
    var tDate = $("#SearchToDate").datepicker("getDate");
    var diff = new Date(tDate - fDate);
    var days = diff / 1000 / 60 / 60 / 24;
    return days;
}