/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

var numberofRows = 0;
var autogeneratednumber1;

function PostingVoucherMaster1()
{
    var financialYear = getUserSessionElement(seCurrentFinancialYear);
    $("#dashboardOrderListId").text("").append('<a href="javascript:void(0)" data-toggle="tab" onclick="displayFinanceHorizontalBar()">Financial Management</a> > <a href="javascript:void(0)" data-toggle="tab" onclick="financeTransactionMenuTabs()">Transaction Master</a> > <a href="javascript:void(0)" data-toggle="tab" onclick="PostingVoucherMaster1()">Voucher Posting</a>');

    $("#dashboardBodyMainDiv").text("").append('<div id="voucherPostingDivId"></div>');
    $("#voucherPostingDivId").text("").append('<div id="voucherPostingTabMenu" />');

    $("#voucherPostingTabMenu").append('<div id="voucherPostingTopMainMenu" class="row" />');
    $("#voucherPostingTabMenu").append('<div id="voucherPostingMainMenu" class="row" />');
    $("#voucherPostingTabMenu").append('<div id="voucherPostingListMainMenu" class="row" />');
    if (checkUserPrivelege(pvViewVoucherPosting)) {

        $("#voucherPostingTopMainMenu").append('<div id="voucherPostingMainPanel" class="panel panel-blue" />');
        $("#voucherPostingMainPanel").append('<div id="voucherPostingMainHeading" class="panel-heading" />');
        $("#voucherPostingMainHeading").append('<div class="panel-title" a data-toggle="collapse" style="font-weight:bold;font-size:15px;" data-parent="#accordion2" href="#collapseOne1"><center>Voucher Approval</center><div class="pull-right" style="position: relative;bottom: 15px;cursor:pointer;" id="voucherpostingColDiv"><span class="glyphicon glyphicon-minus-sign"></span></div></div>');
        $("#voucherPostingMainPanel").append('<div id="collapseOne1" class="panel-collapse collapse in pal" />');
        $("#voucherpostingColDiv").click(function () {
            $("#collapseOne1").toggle();
            if ($("#voucherpostingColDiv span").hasClass("glyphicon-minus-sign")) {
                $("#voucherpostingColDiv").text("").append("<span class='glyphicon glyphicon-plus-sign'></span>");
            } else {
                $("#voucherpostingColDiv").text("").append("<span class='glyphicon glyphicon-minus-sign'></span>");
            }
        });
        $("#collapseOne1").append('<div id="voucherPostingMainBody" class = "panel-body " />');
        $("#voucherPostingMainBody").append('<div id="panelRow" class="form-horizontal" />');

        $("#voucherPostingMainBody").append('<center><span id="voucherPostingMessageDiv"></span></center>');
        $("#voucherPostingMainBody").append('<div id="voucherPostingBodyDiv" class="row" />');
        $("#voucherPostingBodyDiv").append("<span class='pull-right' style='font-size: 15px;'><strong>Financial Year : " + financialYear + "</strong></span>");
        $("#voucherPostingBodyDiv").append("<div id='pregsuccessBefore'></div>");
        $("#voucherPostingBodyDiv").append("<input type='hidden' id='saveorupdate' value='save'>");
        $("#voucherPostingBodyDiv").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="ddo">DDO </label><select class="form-control" name="ddo" id="DDO" onchange=getLocationBasedOnDDOInReceiptVoucher()></select>'
                + '</div><div class="form-group col-lg-6"><label for="location">Location </label><select class="form-control" id="location"></select></div></div>');
        $("#voucherPostingBodyDiv").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="fundType">Fund Type </label><select class="form-control" name="fundType" id="fundType"></select>'
                + '</div><div class="form-group col-lg-6"><label for="budgetHead">Budget Head </label><select class="form-control" id="budgetHead"></select></div></div>');
        $("#voucherPostingBodyDiv").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="manualVoucherNumber">Manual Voucher Number</label><input type="text" class="form-control" name="manualVoucherNumber" id="manualVoucherNo" onkeypress="return validateNumber(event)">'
                + '</div><div class="form-group col-lg-6"><label for="voucherAmount">Voucher Amount </label><input type="text" class="form-control" id="voucherAmount"></div></div>');

        $("#voucherPostingBodyDiv").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="fromDate">From Date<span class="require">*</span> </label><input type="text" class="form-control" id="fromDate" placeholder="MM/DD/YYYY" <span id="fromDateErr" class="text-danger"></span></div>'
                + '<div class="form-group col-lg-6"><label for="toDate">To Date<span class="require">*</span><span id="toDateErr" class="text-danger"></span> </label><input type="text" class="form-control" id="toDate" placeholder="MM/DD/YYYY"></div></div>');
//    <span id="toDateErr" class="text-danger"></span>
        $("#fromDate").datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd/mm/yy",
            yearRange: '-0:+50',
            minDate: '+0D'
        });

        $("#toDate").datepicker({
            changeYear: true,
            changeMonth: true,
            dateFormat: "dd/mm/yy",
            yearRange: '-0:+50',
            minDate: '+0D'
        });
        $("#toDate").keypress(function (event) {
            event.preventDefault();
        });
        $("#fromDate").keypress(function (event) {
            event.preventDefault();
        });
        $("#voucherPostingBodyDiv").append('<div class="col-lg-12"><div class="form-group col-lg-6"><label for="voucherType">Voucher Type<span class="require">*</span></label><select class="form-control" name="voucherType" id="voucherType"></select><span id="voucherTypeErr" class="text-danger"></span>'
                + '</div><div class="form-group col-lg-6"><label for="totalRecords">Total No. of Records </label><input type="text" class="form-control" id="totalNoOfRecords"></div></div>');
        $("#voucherPostingBodyDiv").append("<div class='form-group' id='changeButton'><center><button onclick=viewPostingVoucherListMaster() id='postSearch' class='btn btn-success' style='height:40px;width:80px'>Search</button>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button id='resetButton' onclick=resetAllValuesInVoucherPosting('voucherPostingMainBody') class='btn btn-warning' style='height:40px;width:80px'>Reset</button></center></div>");

        $("#voucherPostingListMainMenu").text("").append('<div id="voucherPostingListPanel" class="panel panel-blue" />');
        $("#voucherPostingListPanel").append('<div id="voucherPostingListHeading" class="panel-heading" />');
        $("#voucherPostingListHeading").append('<class="panel-title" a data-toggle="collapse" style="font-weight:bold;font-size:15px;" data-parent="#accordion2" href="#collapseOne2"><center>List of Voucher Approval(s)</center><div class="pull-right" style="position: relative;bottom: 15px;cursor:pointer;" id="voucherPostingListColDiv"><span class="glyphicon glyphicon-minus-sign"></span></div></div>');

        $("#voucherPostingListPanel").append('<div id="collapseOne2" class="panel-collapse collapse in pal" />');
        //voucherPostingListColDiv
        $("#voucherPostingListColDiv").click(function () {
            $("#collapseOne2").toggle();
            if ($("#voucherPostingListColDiv span").hasClass("glyphicon-minus-sign")) {
                $("#voucherPostingListColDiv").text("").append("<span class='glyphicon glyphicon-plus-sign'></span>");
            } else {
                $("#voucherPostingListColDiv").text("").append("<span class='glyphicon glyphicon-minus-sign'></span>");
            }
        });
        $("#collapseOne2").append("<div id='listpanelMainBody' class = 'panel-body' />");
        $("#listpanelMainBody").append("<div id='listpanelRow' class='row' />");

        $("#listpanelMainBody").append("<div id='pregresssuccessBefore'>");
        $("#listpanelRow").append("<div id='ErrorMessageDiv'  />");
        $("#listpanelRow").append("<div id='voucherPostlistpanelRow' class='table-responsive' />");

//    setTimeout(function () {
//        getDDOforReceiptVoucher("", "DDO");
//    }, 200);

        setTimeout(function () {
            viewOptionIdName("budget/master/FundType/View", "", "description", "fundType", "Fund Type");
        }, 200);

        setTimeout(function () {
            viewOptionIdName("hrms/common/BudgetHead/View", "", "budgetHead", "budgetHead", "Budget Head");
        }, 300);

        var voucherTypeOptions = ["Receipt-Voucher", "Payment-Voucher", "Contra-Voucher", "Journal-Voucher"];
        getHardCodedOptions("voucherType", "Voucher Type", voucherTypeOptions);

        getLoggedInDDOLocationInDropDown("DDO", "location");
    }
}

function PostingVoucherValidation() {
    var result = 1;
    var voucherType = $("#voucherType").val();
    var fromDate = $("#fromDate").val();
    var toDate = $("#toDate").val();
    var DDO = $("#DDO").val();
    var fundType = $("#fundType").val();
    var budgetHead = $("#budgetHead").val();
    var manualVoucherNo = $("#manualVoucherNo").val();
    var voucherAmount = $("#voucherAmount").val();
    if (voucherType == null || voucherType == "") {
        $("#voucherType").focus();
        displaySmallErrorMessages("voucherTypeErr", "Please Select Voucher Type");
        result = 0;
    } else if (voucherType != null || voucherType != "") {
        $("#voucherTypeErr").text("");
    }
    if (fromDate == null || fromDate == "") {
        $("#fromDate").focus();
        displaySmallErrorMessages("fromDateErr", "Please Enter From Date");
        result = 0;
    } else if (fromDate != null || fromDate != "") {
        $("#fromDateErr").text("");
    }
    if (toDate == null || toDate == "") {
        $("#fromDate").focus();
        displaySmallErrorMessages("toDateErr", "Please Enter To Date");
        result = 0;
    } else if (toDate != null || toDate != "") {
        $("#toDateErr").text("");
    }

    if (result != 0) {
        SearchPostingVoucherDetails();
    }
}

function SearchPostingVoucherDetails() {
    var voucherType = $("#voucherType").val();
    var fromDate = $("#fromDate").val();
    var toDate = $("#toDate").val();
    var DDO = $("#DDO").val();
    var fundType = $("#fundType").val();
    var budgetHead = $("#budgetHead").val();
    var manualVoucherNo = $("#manualVoucherNo").val();
    var voucherAmount = $("#voucherAmount").val();

    var sno = 0;
    $.post(server_base_url + "financial/transaction/ReceiptVoucher/Save", {
        receiptvoucherJson: JSON.stringify(receiptVoucherJson),
        userid: sessionStorage.getItem("userId")
    }).done(function (bdata) {
        if (bdata == fail) {
            displayErrorMessages("pregsuccessBefore", "Invalid username / password" + "");
        } else if (bdata == unauthorized || bdata.statuscode == unauthorized) {
            displayErrorMessages("pregsuccessBefore", unauthorizedMessage + "");
        } else if (bdata == statusException) {
            displayErrorMessages("pregsuccessBefore", statusExceptionMessage + "");
        } else if (bdata == invalidSession) {
            callSessionTimeout();
        } else if (bdata == null) {
            displayErrorMessages("pregsuccessBefore", "No User available" + "");
        } else {
            for (var i = bdata.length - 1; i >= 0; i--) {
                sno++;
                var objjson = {
                    objId: bdata[i]._id.$oid,
                    voucherNo: bdata[i].voucherNo,
                    voucherDate: bdata[i].voucherDate,
                    fundType: bdata[i].fundType,
                    budgetHead: bdata[i].budgetHead,
                    ledgerCategory: bdata[i].ledgerCategory,
                    isGrant: bdata[i].isGrant,
                    ledgerList: bdata[i].ledgerList,
                    totalDrAmount: bdata[i].totalDrAmount,
                    totalCrAmount: bdata[i].totalCrAmount,
                    narration: bdata[i].narration,
                    paymentMode: bdata[i].paymentMode,
                    chequeNo: bdata[i].chequeNo,
                    chequeDate: bdata[i].chequeDate,
                    chequeBankName: bdata[i].chequeBankName,
                    chequeAmount: bdata[i].chequeAmount,
                    inFavorOf: bdata[i].inFavorOf,
                    chequeRemarks: bdata[i].chequeRemarks,
                    bankAccountNo: bdata[i].bankAccountNo,
                    bankName: bdata[i].bankName,
                    bankAmount: bdata[i].bankAmount,
                    bankRemarkst: bdata[i].bankRemarkst
                };
                objjson = JSON.stringify(objjson);
                $("#displayListOfPostedVouchersTableBody").append("<tr id='" + bdata[i].status + "' style='cursor:pointer;' >"
                        + "<td>" + sno + "</td>"
                        + "<td style='cursor:pointer;'>CB/RV-" + bdata[i].voucherNo + "</td>"
                        + "<td style='cursor:pointer;'>" + bdata[i].fundType + "</td>"
                        + "<td style='cursor:pointer;'>" + bdata[i].totalDrAmount + "</td>"
                        + "<td style='cursor:pointer;'>" + bdata[i].totalCrAmount + "</td>"
                        + "<td style='cursor:pointer;'>" + bdata[i].paymentMode + "</td>"
                        + "<td style='cursor:pointer;' onclick=updateReceiptVoucher('" + encodeURI(objjson) + "')>" + ' <button type="button"  class="btn btn-success mr5"style="align:center;color:white"  >EDIT</button>' + "</td>"
                        + "<td onclick=deleteReceiptVoucher('" + bdata[i]._id.$oid + "')>" + ' <button type="button" class="btn btn-danger mr5"  style="align:center;color:white" >DELETE</button>' + "</td></tr>");
            }
        }
    });
}

function viewPostingVoucherListMaster() {
    if (checkUserPrivelege(pvViewVoucherPosting)) {

        $("#voucherPostlistpanelRow").text("").append("<div class='tab-pane' id='viewUser'/>");
        $("#viewUser").append("<div class='table-responsive' id='viewUserSectionTableDiv' />");
        $("#viewUserSectionTableDiv").append("<table class='table table-bordered table-warning mb30' id='displayListOfPostedVouchersTable' />");
        $("#displayListOfPostedVouchersTable").append("<thead class=''><tr>"

                + " <th> S.No</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Voucher Number</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Voucher Date</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Fund Type</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Budget Head</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Voucher Amount</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Voucher Type</th>"
                + "<th style='min-width:30%;width:auto;'><i ></i>Narration</th>"
                + "<th style='min-width:1%;width:80px;''><i class='fa'></i>View</th>"
                + "</tr></thead>");

        var result = 1;
        var voucherType = $("#voucherType").val();
        var fromDate = $("#fromDate").val();
        var toDate = $("#toDate").val();
        var DDO = $("#DDO").val();
        var location = $("#location").val();
        var fundType = $("#fundType").val();
        var budgetHead = $("#budgetHead").val();
        var manualVoucherNo = $("#manualVoucherNo").val();
        var voucherAmount = $("#voucherAmount").val();
        var noOfDays = checkFromDateAndToDateCashBookReport();
        if (fromDate == null || fromDate == "" || toDate == null || toDate == "" || voucherType == null || voucherType == "") {
            result = 0;
            displayLargeErrorMessagesInCenterInRed("pregsuccessBefore", "Please fill all mandatory fields");
        } else {
            if (noOfDays < 0) {
                displaySmallErrorMessages("toDateErr", "To Date should be greater than or equal to From Date");
                result = 0;
            } else {
                $("#toDateErr").text("");
//        if (result != 0) {
                $.get(server_base_url + "financial/transaction/VoucherPosting/Search", {
                    voucherType: voucherType,
                    fromDate: fromDate,
                    toDate: toDate,
                    DDO: DDO,
                    location: location,
                    fundType: fundType,
                    budgetHead: budgetHead,
                    manualVoucherNo: manualVoucherNo,
                    voucherAmount: voucherAmount
                }).done(function (bdata) {

                    if (bdata == fail) {
//            displayLargeErrorMessages("pregsuccessBefore", "" + failMessage + "<br /><br />");
//            displayLargeErrorMessages("pregsuccessAfter", "" + failMessage + "<br /><br />");
                    } else if (bdata == unauthorized || bdata.statuscode == unauthorized) {
                        $("#ErrorMessageDiv").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>No Data Available..<strong></div></center>");
                    } else if (bdata == invalidSession) {
                        callSessionTimeout();
                    } else if (bdata == statusException) {
                        $("#ErrorMessageDiv").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>No Data Available..<strong></div></center>");
                    } else {
                        if (bdata != null) {
                            if (bdata.length > 0) {
                                var sno = 0;
                                $("#displayListOfPostedVouchersTable").append("<tbody id='displayListOfPostedVouchersTableBody' class='table-striped table-bordered' />");
//                    for (var i = 0; i < bdata.length; i++) {
                                for (var i = bdata.length - 1; i >= 0; i--) {
                                    sno++;
                                    var obj = bdata[i].value;

                                    var objjson = {
                                        objId: obj._id,
                                        DDO: obj.DDO,
                                        ddoName: obj.ddoName,
                                        location: obj.location,
                                        locationName: obj.locationName,
                                        manualVoucherNo: obj.manualVoucher,
                                        voucherNo: obj.voucherNo,
                                        voucherDate: obj.voucherDate,
                                        fundType: obj.fundType,
                                        budgetHead: obj.budgetHeadName,
                                        ledgerCategory: obj.ledgerCategory,
                                        isGrant: obj.isGrant,
                                        ledgerList: obj.ledgerList,
                                        totalDrAmount: obj.totalDrAmount,
                                        totalCrAmount: obj.totalCrAmount,
                                        narration: obj.narration,
                                        paymentMode: obj.paymentMode,
                                        chequeList: obj.chequeList,
                                        bankPaymentList: obj.bankPaymentList,
//                                        chequeNo: obj.chequeNo,
//                                        chequeDate: obj.chequeDate,
//                                        chequeBankName: obj.chequeBankName,
//                                        chequeAmount: obj.chequeAmount,
//                                        chequeRemarks: obj.chequeRemarks,
                                        instrumentNo: obj.instrumentNo,
                                        instrumentDate: obj.instrumentDate,
                                        instrumentBankName: obj.instrumentBankName,
                                        instrumentAmount: obj.instrumentAmount,
//                                        inFavorOf: obj.inFavorOf,
                                        instrumentRemarks: obj.instrumentRemarks,
//                                        bankAccountNo: obj.bankAccountNo,
//                                        bankName: obj.bankName,
//                                        bankAmount: obj.bankAmount,
//                                        bankRemarkst: obj.bankRemarkst,
                                        voucherName: obj.voucherName,
                                        forLocation: obj.forLocation,
                                        createDate: obj.createDate,
                                        createdBy: obj.createdBy,
                                        status: obj.status,
                                        postingStatus: "Posted"

                                    };
                                    if (voucherType == "Journal-Voucher") {
                                        budgetHead = obj.budgetHead;
                                    }
                                    objjson = JSON.stringify(objjson);
                                    $("#voucherPostingMainMenu").append("<div id='ListPanel234' />");
                                    $("#displayListOfPostedVouchersTableBody").append("<tr id='" + obj._id + "' style='cursor:pointer;' >"
                                            + "<td>" + sno + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.voucherNo + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.voucherDate + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.fundType + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.budgetHeadName + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.totalDrAmount + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.voucherName + "</td>"
                                            + "<td style='cursor:pointer;'>" + obj.narration + "</td>");
                                    if (checkUserPrivelege(pvVoucherPostingDetails)) {
                                        $("#" + obj._id).append("<td style='cursor:pointer;' onclick=viewDetailsOfVoucherToPost('" + encodeURI(objjson) + "','ListPanel234')>" + ' <button type="button"  class="btn btn-success"style="align:center;color:white"  >View Details</button>' + "</td>");
                                    }
                                }
                                $('#displayListOfPostedVouchersTable').dataTable();
                                $("#ListPanel234").text("");
                                $("#ErrorMessageDiv").text("");

                            }
                        }
                    }
                });
            }
        }
    }
}
function  viewDetailsOfVoucherToPost(obj, DivId) {
    if (checkUserPrivelege(pvVoucherPostingDetails)) {
        var objectValue = obj;
        obj = decodeURI(obj);
        obj = JSON.parse(obj);
        $("#displayListOfPostedVouchersTable tr").css("background-color", "white");
        $("#displayListOfPostedVouchersTable tr" + "#" + obj.objId).css("background-color", "rgba(10, 129, 156, 0.3)");

        $("#" + DivId).text("").append("<h4 style='color:red'><center><u><b>Voucher Details</b></u> </center></h4><br><div id='row1' class='row'>");
        $("#row1").append("<div class='col-sm-2'/><label class='col-sm-2'><b>DDO</b></label><label class='col-sm-2'>" + obj.ddoName + "</label>");
        $("#row1").append("<div class='col-sm-1'/><label class='col-sm-2'><b>Location</b></label><label class='col-sm-2'>" + obj.locationName + "</label>");
        $("#ListPanel234").append("<div id='row2' class='row'>");
        $("#row2").append("<div class='col-sm-2'/><label class='col-sm-2'><b>Voucher No.</b></label><label class='col-sm-2'>" + obj.voucherNo + "</label>");
        $("#row2").append("<div class='col-sm-1'/><label class='col-sm-2'><b>Manual Voucher No.<b></label><label class='col-sm-2'>" + obj.manualVoucherNo + "</label>");
        $("#ListPanel234").append("<div id='row3' class='row'>");
        $("#row3").append("<div class='col-sm-2'/><label class='col-sm-2'><b>Voucher Name</b></label><label class='col-sm-2'>" + obj.voucherName + "</label>");
        $("#row3").append("<div class='col-sm-1'/><label class='col-sm-2'><b>Voucher Date<b></label><label class='col-sm-2'>" + obj.voucherDate + "</label>");
        $("#ListPanel234").append("<div id='row4' class='row'>");
        $("#row4").append("<div class='col-sm-2'/><label class='col-sm-2'><b>Posting Date</b></label><label class='col-sm-2'><input  type='text' style='width:88px' name='postingDate'  id='postingDate' 'onkeydown='return false;'></input></label>");
        $("#row4").append("<div class='col-sm-1'/><label class='col-sm-2'><b>Fund Type</b></label><label class='col-sm-2'>" + obj.fundType + "</label>");

        $("#ListPanel234").append("<div id='row5' class='row'>");
        $("#row5").append("<div class='col-sm-2'/><label class='col-sm-2'><b>Budget Head</b></label><label class='col-sm-2'>" + obj.budgetHead + "</label>");
        $("#row5").append("<div class='col-sm-1'/><label class='col-sm-2'><b>Ledger Category</b></label><label class='col-sm-2'>" + obj.ledgerCategory + "</label>");
        $("#ListPanel234").append("<div id='row6' class='row'>");
        $("#row6").append("<div class='col-sm-2'/><label class='col-sm-2'><b>Voucher Amount</b></label><label class='col-sm-2'>" + obj.totalDrAmount + "</label>");

//        $(function () {
        var start = new Date();
        $('#postingDate').datepicker({
            startDate: start
        });
//        });


        $("#postingDate").datepicker({});
        $("#postingDate").datepicker().datepicker("setDate", new Date());
        $("#row6").append("<div class='col-sm-1'/><label class='col-sm-2'><b>Narration</b> </label><textarea  readonly >" + obj.narration + "</textarea>");

        $("#ListPanel234").append("<div id='row7' class='row'>");
        $("#row7").append("<div id='row7_1' class='col-sm-1'>");
        $("#row7").append("<div id='row7_2' class='col-sm-10'>");

        $("#row7_2").append("<div id='panelRowForTable' class='row' />");
        $("#panelRowForTable").append("<div id='PaymentVoucherListAddPanel' class='panel panel-blue' />");
        $("#PaymentVoucherListAddPanel").append("<div id='PaymentVoucherListAddPanelHeading' class='panel-heading' />");
        $("#PaymentVoucherListAddPanelHeading").append("<h4 id='firstHeaderOfPaymentVoucherListAdd' class='panel-title' />");
        $("#firstHeaderOfPaymentVoucherListAdd").append("<div class='panel-title' a data-toggle='collapse' style='font-weight:bold;font-size:15px;' data-parent='#accordion2' href='#collapseOne31'><center>List of Ledger Amount Detail(s) </center><div class='pull-right' style='position: relative;bottom: 15px;cursor:pointer;' id='colvoucherPostingdiv'><span class='glyphicon glyphicon-minus-sign'></span></div></div>");
        $("#PaymentVoucherListAddPanel").append("<div id='collapseOne31' class='panel-collapse collapse in' />");

        $("#colvoucherPostingdiv").click(function () {
            $("#collapseOne31").toggle();
            if ($("#colvoucherPostingdiv span").hasClass("glyphicon-minus-sign")) {
                $("#colvoucherPostingdiv").text("").append("<span class='glyphicon glyphicon-plus-sign'></span>");
            } else {
                $("#colvoucherPostingdiv").text("").append("<span class='glyphicon glyphicon-minus-sign'></span>");
            }
        });


        $("#collapseOne31").append("<div id='paymentVoucherListAddlistpanelMainBody' class = 'panel-body' />");
        $("#paymentVoucherListAddlistpanelMainBody").append("<div id='paymentVoucherlistAddpanelRow' class='row' />");
        viewPostingVoucherAddList('paymentVoucherlistAddpanelRow');
        addPostingVoucherRows("displayPaymentVoucherAddTableBody", obj.ledgerList);

        $("#ListPanel234").append("<div id='row8' class='row'>");
        $("#row8").append("<div id='row8_1' class='col-lg-6'>");
        $("#row8").append("<div id='row8_2' class='col-lg-6'>");

        $("#row8_1").append("<div id='panelRowForListofCheque' />");
        $("#panelRowForListofCheque").append("<div id='ReceiptVoucherPaymentListAddPanel' class='panel panel-blue' />");
        $("#ReceiptVoucherPaymentListAddPanel").append("<div id='ReceiptVoucherPaymentListAddPanelHeading' class='panel-heading' />");
        $("#ReceiptVoucherPaymentListAddPanelHeading").append("<h4 id='firstHeaderOfReceiptVoucherPaymentListAdd1' class='panel-title' />");
        $("#firstHeaderOfReceiptVoucherPaymentListAdd1").append("<div  style='font-weight:bold;font-size:15px;' ><center>List of Cheque Payment</center></div>");
        $("#panelRowForListofCheque").append("<div id='listpanelBodys' class = 'panel-body' />");
        $("#listpanelBodys").append("<div id='pregsuccessBeforelist'></div>");


        $("#row8_2").append("<div id='panelRowForListofBank' class='row'/>");
        $("#panelRowForListofBank").append("<div id='ReceiptVoucherPaymentListAddPanel1' class='panel panel-blue' />");
        $("#ReceiptVoucherPaymentListAddPanel1").append("<div id='ReceiptVoucherPaymentListAddPanelHeading1' class='panel-heading' />");
        $("#ReceiptVoucherPaymentListAddPanelHeading1").append("<h4 id='firstHeaderOfReceiptVoucherPaymentListAdd2' class='panel-title' />");
        $("#firstHeaderOfReceiptVoucherPaymentListAdd2").append("<div  style='font-weight:bold;font-size:15px;' ><center>List of Bank Payment</center></div>");
        $("#panelRowForListofBank").append("<div id='listpanelMainBodys2' class = 'panel-body' />");
        $("#listpanelMainBodys2").append("<div id='pregsuccessBeforelist2'></div>");

        viewchequeDetailsAddList('listpanelBodys');
        viewBankDetailsAddList('listpanelMainBodys2');
        addChequeDetailsVoucherRows('displayPaymentTableBody1', obj.chequeList);
        addBankDetailsVoucherRows('displayPaymentTableBody2', obj.bankPaymentList);
//            if (obj.paymentMode == "Cheque") {
//                $("#ListPanel234").append("<div id='rowOfChequeDetails' class='row'>");
//                $("#rowOfChequeDetails").append("<div id='rowOfChequeDetails1' class='col-sm-1'></div>");
//                $("#rowOfChequeDetails").append("<div id='rowOfChequeDetails2' class='col-sm-10'>");
//                viewchequeDetailsAddList('chequeDetailsRow');
//                addChequeDetailsVoucherRows("displayChequeDetailsVoucherAddTableBody", encodeURI(JSON.stringify(obj)));
//            } else if (obj.paymentMode == "Bank") {
//                $("#ListPanel234").append("<div id='rowOfChequeDetails' class='row'>");
//                $("#rowOfChequeDetails").append("<div id='rowOfChequeDetails1' class='col-sm-1'></div>");
//                $("#rowOfChequeDetails").append("<div id='rowOfChequeDetails2' class='col-sm-10'>");
//                viewBankDetailsAddList('chequeDetailsRow');
//                addBankDetailsVoucherRows("displayChequeDetailsVoucherAddTableBody", encodeURI(JSON.stringify(obj)));
//            }


        $("#ListPanel234").append("<div id='row9' class='row'>");
        if (checkUserPrivelege(pvSaveVoucherPosting)) {
            $("#row9").append("<div  class='col-xs-12' /><center><button type='button' style='margin-bottom:15px' value='Save' class='btn btn-success pull-center' onclick=postThisVoucher('" + objectValue + "')>Post Selected Voucher</button></center></div>");
        }
        $("#row9").append("");
    }
}

function  viewPostingVoucherAddList(DivId) {
    $("#" + DivId).text("").append("<div class='tab-pane' id='viewPaymentVoucherAdd'/>");
    $("#viewPaymentVoucherAdd").append("<div class='table-responsive' id='viewPaymentVoucherAddTableDiv' />");
    $("#viewPaymentVoucherAddTableDiv").append("<table class='table table-bordered table-striped table-warning mb30' id='displayPaymentVoucherAddTable' />");
    $("#displayPaymentVoucherAddTable").append("<thead class=''><tr>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Sl No.</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Dr/Cr</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Group</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Particulars</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Dr Amount</th>"
            + "<th style='min-width:30%;width:auto;'><i ></i>Cr Amount</th>"
            + "<th style='min-width:30%;width:auto;'><i class='fa'></i>Short Narration</th>"
            + "</tr></thead>");
    $("#displayPaymentVoucherAddTable").append("<tbody id='displayPaymentVoucherAddTableBody' class='table-striped table-bordered' />");
}
function  viewchequeDetailsAddList(divId) {
    $("#" + divId).text("").append("<div id='ErrorDiv'/>");
    $("#" + divId).text("").append("<div id='listpanelRow1' class='row' />");
    $("#listpanelRow1").text("").append("<div class='tab-pane' id='DatatablemainDiv1'/>");
    $("#DatatablemainDiv1").text("").append("<div class='table-responsive' id='viewDataTableDiv1' />");
    $("#viewDataTableDiv1").append("<table class='table table-bordered table-striped table-warning mb30' id='displayPaymentTable1' />");
    $("#displayPaymentTable1").append("<thead class=''><tr>"

            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Cheque Number</th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Cheque Date</th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Bank Name</th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Cheque Amount</th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>In Favor Of</th>"
            + "</tr></thead>");
    $("#displayPaymentTable1").append("<tbody id='displayPaymentTableBody1' class='table-striped table-bordered' />");

}

function  viewBankDetailsAddList(divId) {

    $("#" + divId).text("").append("<div id='ErrorDiv'/>");
    $("#" + divId).text("").append("<div id='listpanelRow2' class='row' />");
    $("#listpanelRow2").text("").append("<div class='tab-pane' id='DatatablemainDiv2'/>");
    $("#DatatablemainDiv2").text("").append("<div class='table-responsive' id='viewDataTableDiv2' />");
    $("#viewDataTableDiv2").append("<table class='table table-bordered table-striped table-warning mb30' id='displayPaymentTable' />");
    $("#displayPaymentTable").append("<thead class=''><tr>"

            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Transfer Mode</th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Account Number </th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Bank Name </th>"
            + "<th style='min-width:10%;width:auto;'><i class='fa'></i>Bank Amount</th>"
            + "</tr></thead>");
    $("#displayPaymentTable").append("<tbody id='displayPaymentTableBody2' class='table-striped table-bordered' />");

}


function addPostingVoucherRows(DivId, ledgerList)
{
    if (ledgerList != null) {
        for (var i = 0; i < ledgerList.length; i++) {
            var groupId = 'group' + i;
            var ledgerId = 'ledger' + i;
            var drAmountId = 'drAmount' + i;
            var crAmountId = 'crAmount' + i;
            var drCrId = 'drCrId' + i;
            var j = i + 1;
            $("#" + DivId).append("<tr style='cursor:pointer;' >"
                    + "<td style='cursor:pointer;'>" + j + "</td>"
                    + "<td style='cursor:pointer;'><label   id='" + drCrId + "' >" + ledgerList[i].DrCr + "</select></td>"
                    + "<td style='cursor:pointer;'><label>" + ledgerList[i].groupName + "</label></td>"
                    + "<td style='cursor:pointer;'><label>" + ledgerList[i].ledgerName + "</label></td>"
                    + "<td style='cursor:pointer;'><label> " + ledgerList[i].drAmount + "</label></td>"
                    + "<td style='cursor:pointer;'><label> " + ledgerList[i].crAmount + "</label></td>"
                    + "<td style='cursor:pointer;'><label> " + ledgerList[i].shortNarration + "</label></td>"
                    + "</tr></thead>");
        }
    }
}

function addChequeDetailsVoucherRows(DivId, chequeList)
{
    //obj = decodeURI(obj);
    // obj = JSON.parse(obj);

    if (chequeList != null) {
        for (var i = 0; i < chequeList.length; i++) {
            $("#" + DivId).append("<tr style='cursor:pointer;' >"
                    + "<td style='cursor:pointer;'><label>" + chequeList[i].chequeNo + "</label></td>"
                    + "<td style='cursor:pointer;'><label>" + chequeList[i].chequeDate + "</label></td>"
                    + "<td style='cursor:pointer;'><label> " + chequeList[i].chequeBankName + "</label></td>"
                    + "<td style='cursor:pointer;'><label> " + chequeList[i].chequeAmount + "</label></td>"
                    + "<td style='cursor:pointer;'><label> " + chequeList[i].inFavorOf + "</label></td>"
                    + "</tr></thead>");
        }
    }

//    if (obj != null) {
//        $("#" + DivId).append("<tr style='cursor:pointer;' >"
//                + "<td style='cursor:pointer;'><label   >" + obj.chequeNo + "</select></td>"
//                + "<td style='cursor:pointer;'><label>" + obj.chequeDate + "</label></td>"
//                + "<td style='cursor:pointer;'><label>" + obj.chequeBankName + "</label></td>"
//                + "<td style='cursor:pointer;'><label> " + obj.chequeAmount + "</label></td>"
//                + "<td style='cursor:pointer;'><label> " + obj.inFavorOf + "</label></td>"
//                + "<td style='cursor:pointer;'><label> " + obj.chequeRemarks + "</label></td>"
//                + "</tr></thead>");
//    }
}

function addBankDetailsVoucherRows(DivId, bankPaymentList)
{
    if (bankPaymentList != null) {
        for (var i = 0; i < bankPaymentList.length; i++) {
            $("#" + DivId).append("<tr style='cursor:pointer;' >"
                    + "<td style='cursor:pointer;'><label>" + bankPaymentList[i].transferMode + "</label></td>"
                    + "<td style='cursor:pointer;'><label>" + bankPaymentList[i].bankAccountNo + "</label></td>"
                    + "<td style='cursor:pointer;'><label>" + bankPaymentList[i].bankName + "</label></td>"
                    + "<td style='cursor:pointer;'><label>" + bankPaymentList[i].bankAmount + "</label></td>"
                    + "</tr></thead>");
        }
    }
}

function postThisVoucher(obj) {
    if (checkUserPrivelege(pvSaveVoucherPosting)) {
        obj = decodeURI(obj);
        obj = JSON.parse(obj);
        var pvId = obj.objId;
        var voucherName = obj.voucherName;
        var postingDate = $("#postingDate").val();
//    if (obj.voucherName == "PaymentVoucher") {

        $.post(server_base_url + "financial/transaction/VoucherPosting/UpdatePostingStatus", {
            paymentVoucherJson: JSON.stringify(obj),
            userid: sessionStorage.getItem("userId"),
            pvId: pvId,
            postingDate: postingDate,
            voucherName: voucherName

        }).done(function (data) {
            // $("#ErrorMessageDiv").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>Posted Succesfully.....<strong></div></center>");
            $("#ListPanel234").text("");
            displaySuccessMessages("ErrorMessageDiv", "Posted Succesfully...", "");
            setTimeout(function () {
                viewPostingVoucherAddList();
            }, 1000);

            clearSuccessMessageAfterTwoSecond("ErrorMessageDiv");
            $("#postSearch").click();
        });
//    } else if (obj.voucherName == "ReceiptVoucher") {
//        $.post(server_base_url + "financial/transaction/VoucherPosting/UpdatePostingStatus", {
//            receiptvoucherJson: JSON.stringify(obj),
//            userid: sessionStorage.getItem("userId"),
//            pvId: pvId,
//            voucherName:voucherName
//        }).done(function(data) {
//            $("#ErrorMessageDiv").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>Posted Succesfully.....<strong></div></center>");
//            $("#ListPanel234").text("");
//            $("#postSearch").click();
//        });
//    } else if (obj.voucherName == "ContraVoucher") {
//        $.post(server_base_url + "financial/transaction/VoucherPosting/UpdatePostingStatus", {
//            contraVoucherJson: JSON.stringify(obj),
//            userid: sessionStorage.getItem("userId"),
//            pvId: pvId,
//            voucherName:voucherName
//        }).done(function(data) {
//            $("#ErrorMessageDiv").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>Posted Succesfully.....<strong></div></center>");
//            $("#ListPanel234").text("");
//            $("#postSearch").click();
//        });
//    } else if (obj.voucherName == "JournalVoucher") {
//        $.post(server_base_url + "financial/transaction/VoucherPosting/UpdatePostingStatus", {
//            JournalVoucherJson: JSON.stringify(obj),
//            userid: sessionStorage.getItem("userId"),
//            pvId: pvId,
//            voucherName:voucherName
//        }).done(function(data) {
//            $("#ErrorMessageDiv").text("").append("<center><div class='col-sm-12'  style='color:red;'><strong>Posted Succesfully.....<strong></div></center>");
//            $("#ListPanel234").text("");
//            $("#postSearch").click();
//        });
//    }
    }
}

function resetAllValuesInVoucherPosting(DivId) {
    $("#ListPanel234").text("");
    $("#fundType").val("");
    $("#budgetHead").val("");
    $("#voucherType").val("");
    $("#totalNoOfRecords").val("");
    $('#' + DivId).find('input:text').val('');
    $('#' + DivId).find('input:checkbox').val('');
    $('#' + DivId).find('input:radio').val('');
    $('#' + DivId).find('input:select').val("");
    $('#' + DivId).find('select').val("");
    $('#SearchErrorMessageDiv').text("");
    $('#SearchErrorMessageDiv').val("");
    $('#ErrorMessageDiv1').text("");
    $('#ErrorMessageDiv1').val("");
    $("#toDateErr").text("")
    $('#toDateErr').val("");
}
